#!/bin/bash
# build_gui.sh - Build the Qt6 GUI for Backup Manager

set -e
set -o pipefail

# Use CC/CXX environment variables if set, otherwise default to gcc/g++
CC_COMPILER=${CC:-gcc}
CXX_COMPILER=${CXX:-g++}

echo "Building Backup Manager GUI..."

# Check for Qt6
if ! pkg-config --exists Qt6Widgets; then
    echo "Error: Qt6 not found. Install with:"
    echo "  Arch Linux: sudo pacman -S qt6-base"
    echo "  Debian/Ubuntu: sudo apt-get install qt6-base-dev"
    exit 1
fi

# Check for json-glib-1.0
if ! pkg-config --exists json-glib-1.0; then
    echo "Error: json-glib-1.0 not found. Install with:"
    echo "  Arch Linux: sudo pacman -S json-glib"
    echo "  Debian/Ubuntu: sudo apt-get install libjson-glib-dev"
    exit 1
fi

# Check for libsodium
if ! pkg-config --exists libsodium; then
    echo "Error: libsodium not found. Install with:"
    echo "  Arch Linux: sudo pacman -S libsodium"
    echo "  Debian/Ubuntu: sudo apt-get install libsodium-dev"
    exit 1
fi

# 1. Generate C sources from Vala library (generate into a build-local directory)
echo "[1/5] Generating C sources from Vala..."
# Use an isolated build directory for valac-generated sources to avoid checking them into git
BUILD_GEN_C_DIR="build/gen-c"
rm -rf "$BUILD_GEN_C_DIR"
mkdir -p "$BUILD_GEN_C_DIR"

# Suppress some warnings generated by Vala-generated C (these warnings come from
# glib/gatomic and const-qualification mismatch in generated C). We prefer to
# keep the Vala-generated sources unchanged and silence these warnings during
# C compilation.

# Detect platform for package selection
UNAME_OUT="$(uname -s 2>/dev/null || echo unknown)"
case "$UNAME_OUT" in
    MINGW*|MSYS*|CYGWIN*)
        # Windows: gio-2.0 only (no gio-unix)
        GIO_PKG="gio-2.0"
        VALA_DEFINES=""
        ;;
    *)
        # Linux/macOS: needs gio-unix-2.0 and POSIX define
        GIO_PKG="gio-2.0 --pkg gio-unix-2.0"
        VALA_DEFINES="-D POSIX"
        ;;
esac

valac --pkg glib-2.0 --pkg $GIO_PKG --pkg json-glib-1.0 \
    --vapidir=vala-extra-vapis --pkg libsodium \
    $VALA_DEFINES \
    libdvx3.vala -C -d "$BUILD_GEN_C_DIR"

# Apply a small patch to generated C to avoid __atomic_load warnings introduced by unix-compatible atomic macros.
# The generated code uses 'g_once_init_enter (&X__once)' which can trigger a warning because the macro expects a volatile pointer.
# We replace calls with a volatile cast so the compiler stops emitting the warning.
if [ -f "$BUILD_GEN_C_DIR/libdvx3.c" ]; then
    echo "Patching generated C to cast g_once_init_enter args to volatile gpointer *"
    chmod +x scripts/patch-gen-c.sh || true
    scripts/patch-gen-c.sh "$BUILD_GEN_C_DIR/libdvx3.c" || true
fi

# 2. Compile generated C code
echo "[2/5] Compiling C library..."

# Set GIO libs based on platform
case "$UNAME_OUT" in
    MINGW*|MSYS*|CYGWIN*)
        GIO_LIBS="gio-2.0"
        ;;
    *)
        GIO_LIBS="gio-2.0 gio-unix-2.0"
        ;;
esac

"$CC_COMPILER" -c -fPIC "$BUILD_GEN_C_DIR/libdvx3.c" -o libdvx3.o \
    $(pkg-config --cflags glib-2.0 $GIO_LIBS json-glib-1.0 libsodium) \
    -I. -I"$BUILD_GEN_C_DIR" -Wno-incompatible-pointer-types -Wno-discarded-qualifiers

# Shared library extension (UNAME_OUT already set above)
case "$UNAME_OUT" in
    MINGW*|MSYS*|CYGWIN*)
        SHARED_EXT="dll"
        SHARED_FLAGS="-shared -Wl,--out-implib,libdvx3.dll.a -Wl,--export-all-symbols"
        ;;
    Darwin)
        SHARED_EXT="dylib"
        SHARED_FLAGS="-dynamiclib -install_name @loader_path/libdvx3.dylib"
        ;;
    *)
        SHARED_EXT="so"
        SHARED_FLAGS="-shared"
        ;;
esac

# Prefer static libsodium (when available) to avoid runtime library mismatches on target systems
SODIUM_STATIC_LINK=""

# Determine if a static libsodium archive contains PIC object files
is_static_lib_pic() {
    local libfile="$1"
    if [ -z "$libfile" ] || [ ! -f "$libfile" ]; then
        return 1
    fi
    if ! command -v readelf >/dev/null 2>&1 || ! command -v ar >/dev/null 2>&1; then
        # Cannot determine; conservatively assume non-PIC
        return 1
    fi
    tmpd=$(mktemp -d)
    (cd "$tmpd" && ar x "$libfile") || { rm -rf "$tmpd"; return 1; }
    # If there are no object files, treat as non-PIC
    shopt -s nullglob
    local found_nonpic=0
    for o in "$tmpd"/*.o; do
        # Look for relocations that indicate non-PIC (PC32 relocations)
        if readelf -r "$o" 2>/dev/null | grep -q -E 'R_386_PC32|R_X86_64_PC32|R_ARM_PC24|R_ARM_V4BX|R_ARM_PREL31|R_AARCH64_PREL32|R_PPC_REL24'; then
            found_nonpic=1
            break
        fi
        # Also reject objects with TEXTREL flags
        if readelf -D "$o" 2>/dev/null | grep -q "TEXTREL"; then
            found_nonpic=1
            break
        fi
    done
    rm -rf "$tmpd"
    [ "$found_nonpic" -eq 0 ] && return 0 || return 1
}

# Check for static libsodium, prefer dynamic if static is present but not PIC (shared libdvx3 requires PIC)
LIBSODIUM_PATHS=(/usr/local/lib/libsodium.a /usr/lib/x86_64-linux-gnu/libsodium.a /usr/lib/libsodium.a)
found_lib=""
for p in "${LIBSODIUM_PATHS[@]}"; do
    if [ -f "$p" ]; then
        found_lib="$p"
        break
    fi
done

if [ "${FORCE_STATIC_LIBSODIUM:-0}" -eq 1 ]; then
    if [ -n "$found_lib" ]; then
        if is_static_lib_pic "$found_lib"; then
            echo "FORCE_STATIC_LIBSODIUM=1: Linking libsodium statically into libdvx3"
            SODIUM_STATIC_LINK='-Wl,-Bstatic -lsodium -Wl,-Bdynamic'
        else
            echo "FORCE_STATIC_LIBSODIUM=1 requested, but static libsodium ($found_lib) is not compiled with -fPIC. Aborting." >&2
            echo "To fix: install/build a PIC-enabled static libsodium (e.g. build libsodium with -fPIC), or unset FORCE_STATIC_LIBSODIUM." >&2
            exit 1
        fi
    else
        echo "FORCE_STATIC_LIBSODIUM=1 requested, but static libsodium (.a) not found. Aborting." >&2
        exit 1
    fi
else
    if [ -n "$found_lib" ]; then
        if is_static_lib_pic "$found_lib"; then
            echo "Static libsodium (PIC) found at $found_lib: linking statically into libdvx3"
            SODIUM_STATIC_LINK='-Wl,-Bstatic -lsodium -Wl,-Bdynamic'
        else
            echo "Static libsodium found at $found_lib but it's not PIC; falling back to shared libsodium to avoid linker errors"
            SODIUM_STATIC_LINK=$(pkg-config --libs libsodium || echo "-lsodium")
        fi
    else
        SODIUM_STATIC_LINK=$(pkg-config --libs libsodium || echo "-lsodium")
    fi
fi

"$CC_COMPILER" $SHARED_FLAGS -o libdvx3.$SHARED_EXT libdvx3.o \
    $(pkg-config --libs glib-2.0 $GIO_LIBS json-glib-1.0) $SODIUM_STATIC_LINK

# 3. Compile backup-manager implementation
echo "[3/5] Compiling backup manager library..."
# Compile the C++ source file (compile .cpp, not the .hpp header)
"$CXX_COMPILER" -c -fPIC backup-manager.cpp -o backup-manager-lib.o \
    -std=c++17 \
    $(pkg-config --cflags glib-2.0 $GIO_LIBS json-glib-1.0 libsodium) \
    -I.

# 4. Run MOC on GUI header
echo "[4/5] Running Qt MOC..."

# Windows MSYS2 fix for Qt6 moc path from pkg-config libexecdir
case "$UNAME_OUT" in
    MINGW*|MSYS*|CYGWIN*)
        if command -v pkg-config >/dev/null 2>&1; then
            libexecdir=$(pkg-config --variable=libexecdir 'Qt6Core >= 6.4.0' 2>/dev/null)
            if [ -n "$libexecdir" ]; then
                libexecdir=$(cygpath -a "$libexecdir")
                moc_candidate="$libexecdir/moc"
                if [ -x "$moc_candidate" ] || [ -x "$moc_candidate.exe" ]; then
                    if [ -x "$moc_candidate" ]; then
                        MOC="$moc_candidate"
                    else
                        MOC="${moc_candidate}.exe"
                    fi
                    RCC="${libexecdir}/rcc"
                    echo "✓ Found moc at Qt6 libexecdir: $MOC"
                fi
            fi
        fi
        # Additional MSYS2 locations: some MSYS2 packages install mocs to share/qt6/bin
        if [ -z "$MOC" ]; then
            if [ -x /mingw64/share/qt6/bin/moc ]; then
                MOC=/mingw64/share/qt6/bin/moc
                RCC=/mingw64/share/qt6/bin/rcc
                echo "✓ Found moc at /mingw64/share/qt6/bin/moc"
            elif [ -x /mingw64/share/qt6/bin/moc.exe ]; then
                MOC=/mingw64/share/qt6/bin/moc.exe
                RCC=/mingw64/share/qt6/bin/rcc.exe
                echo "✓ Found moc at /mingw64/share/qt6/bin/moc.exe"
            fi
        fi
        # Prepend /mingw64/share/qt6/bin to PATH if it exists (so `which moc` finds it)
        if [ -d /mingw64/share/qt6/bin ] && ! echo "$PATH" | grep -q "/mingw64/share/qt6/bin"; then
            export PATH="/mingw64/share/qt6/bin:$PATH"
            echo "Path updated to include MSYS2 Qt6 share bin: /mingw64/share/qt6/bin"
        fi
        ;;
esac

# Find moc and rcc (works on Linux, macOS, Windows/MSYS2)
# Prioritize Qt6-specific tools to avoid Qt5/Qt6 mismatch
if [ -z "$MOC" ]; then
    if [ -n "$QT_MOC_NATIVE" ] && [ -x "$QT_MOC_NATIVE" ]; then
        MOC="$QT_MOC_NATIVE"
        RCC_DIR=$(dirname "$QT_MOC_NATIVE")
        if [ -x "$RCC_DIR/rcc" ]; then
            RCC="$RCC_DIR/rcc"
        else
            RCC=rcc # Fallback to searching in PATH
        fi
    elif [ -x /opt/homebrew/opt/qt/bin/moc ]; then
        MOC=/opt/homebrew/opt/qt/bin/moc
        RCC=/opt/homebrew/opt/qt/bin/rcc
    elif [ -x /opt/homebrew/opt/qt@6/bin/moc ]; then
        MOC=/opt/homebrew/opt/qt@6/bin/moc
        RCC=/opt/homebrew/opt/qt@6/bin/rcc
    elif [ -x /usr/local/opt/qt/bin/moc ]; then
        MOC=/usr/local/opt/qt/bin/moc
        RCC=/usr/local/opt/qt/bin/rcc
    elif [ -x /usr/local/opt/qt@6/bin/moc ]; then
        MOC=/usr/local/opt/qt@6/bin/moc
        RCC=/usr/local/opt/qt@6/bin/rcc
    elif [ -x /opt/homebrew/bin/moc ]; then
        MOC=/opt/homebrew/bin/moc
        RCC=/opt/homebrew/bin/rcc
    elif [ -x /usr/local/bin/moc ]; then
        MOC=/usr/local/bin/moc
        RCC=/usr/local/bin/rcc
    elif [ -x /opt/homebrew/opt/qt6/bin/moc ]; then
        MOC=/opt/homebrew/opt/qt6/bin/moc
        RCC=/opt/homebrew/opt/qt6/bin/rcc
    elif [ -x /usr/local/opt/qt6/bin/moc ]; then
        MOC=/usr/local/opt/qt6/bin/moc
        RCC=/usr/local/opt/qt6/bin/rcc
    elif [ -x /mingw64/bin/moc-qt6 ]; then
        MOC=/mingw64/bin/moc-qt6
        RCC=/mingw64/bin/rcc-qt6
        echo "✓ Found moc-qt6 at /mingw64/bin/"
    elif [ -x /mingw64/bin/moc-qt6.exe ]; then
        MOC=/mingw64/bin/moc-qt6.exe
        RCC=/mingw64/bin/rcc-qt6.exe
        echo "✓ Found moc-qt6.exe at /mingw64/bin/"
    elif [ -x /mingw64/bin/moc6 ]; then
        MOC=/mingw64/bin/moc6
        RCC=/mingw64/bin/rcc6
        echo "✓ Found moc6 at /mingw64/bin/"
    elif [ -x /mingw64/bin/moc6.exe ]; then
        MOC=/mingw64/bin/moc6.exe
        RCC=/mingw64/bin/rcc6.exe
        echo "✓ Found moc6.exe at /mingw64/bin/"
    elif [ -x /mingw64/bin/moc ]; then
        MOC=/mingw64/bin/moc
        RCC=/mingw64/bin/rcc
        echo "✓ Found moc at /mingw64/bin/"
    elif [ -x /mingw64/bin/moc.exe ]; then
        MOC=/mingw64/bin/moc.exe
        RCC=/mingw64/bin/rcc.exe
        echo "✓ Found moc.exe at /mingw64/bin/"
    elif [ -x /mingw64/qt6/bin/moc ]; then
        MOC=/mingw64/qt6/bin/moc
        RCC=/mingw64/qt6/bin/rcc
        echo "✓ Found moc at /mingw64/qt6/bin/"
    elif [ -x /mingw64/qt6/bin/moc.exe ]; then
        MOC=/mingw64/qt6/bin/moc.exe
        RCC=/mingw64/qt6/bin/rcc.exe
        echo "✓ Found moc.exe at /mingw64/qt6/bin/"
    elif [ -x /mingw64/lib/qt6/bin/moc ]; then
        MOC=/mingw64/lib/qt6/bin/moc
        RCC=/mingw64/lib/qt6/bin/rcc
        echo "✓ Found moc at /mingw64/lib/qt6/bin/"
    elif [ -x /mingw64/lib/qt6/bin/moc.exe ]; then
        MOC=/mingw64/lib/qt6/bin/moc.exe
        RCC=/mingw64/lib/qt6/bin/rcc.exe
        echo "✓ Found moc.exe at /mingw64/lib/qt6/bin/"
    elif [ -x /usr/lib/qt6/moc ]; then
        MOC=/usr/lib/qt6/moc
        RCC=/usr/lib/qt6/rcc
    elif [ -x /usr/lib/qt6/libexec/moc ]; then
        MOC=/usr/lib/qt6/libexec/moc
        RCC=/usr/lib/qt6/libexec/rcc
    elif [ -x /mingw64/share/qt6/bin/moc ]; then
        MOC=/mingw64/share/qt6/bin/moc
        RCC=/mingw64/share/qt6/bin/rcc
        echo "✓ Found moc at /mingw64/share/qt6/bin/"
    elif [ -x /mingw64/share/qt6/bin/moc.exe ]; then
        MOC=/mingw64/share/qt6/bin/moc.exe
        RCC=/mingw64/share/qt6/bin/rcc.exe
        echo "✓ Found moc.exe at /mingw64/share/qt6/bin/"
    elif command -v moc-qt6 >/dev/null 2>&1; then
        MOC=moc-qt6
        RCC=rcc-qt6
    elif command -v moc6 >/dev/null 2>&1; then
        MOC=moc6
        RCC=rcc6
    elif command -v moc >/dev/null 2>&1; then
        MOC=moc
        RCC=rcc
    else
        echo "Error: moc not found. Install Qt6 development tools."
        echo "Searched locations:"
        echo "  - macOS Homebrew: /opt/homebrew/opt/qt/bin/moc, /opt/homebrew/opt/qt@6/bin/moc, /opt/homebrew/opt/qt6/bin/moc, /opt/homebrew/bin/moc"
        echo "  - macOS Homebrew (Intel): /usr/local/opt/qt/bin/moc, /usr/local/opt/qt@6/bin/moc, /usr/local/opt/qt6/bin/moc, /usr/local/bin/moc"
        echo "  - MSYS2: /mingw64/bin/moc, /mingw64/bin/moc.exe, /mingw64/qt6/bin/moc, /mingw64/qt6/bin/moc.exe, /mingw64/lib/qt6/bin/moc, /mingw64/lib/qt6/bin/moc.exe"
        echo "  - Linux: /usr/lib/qt6/moc, /usr/lib/qt6/libexec/moc"
        echo "  - PATH: moc-qt6, moc6, moc"
        exit 1
    fi
fi

$MOC backup-manager-gui.hpp -o backup-manager-gui.moc.cpp

echo "[4b/5] Compiling resources..."
if [ -f resources.qrc ] && [ -f dvx3-backup.png ]; then
    echo "Using dvx3-backup.png for resources"
    $RCC resources.qrc -o resources.rcc.cpp
elif [ -f resources.qrc ]; then
    echo "Warning: dvx3-backup.png not found; compiling resources without icon."
    $RCC resources.qrc -o resources.rcc.cpp
else
    echo "Warning: resources.qrc not found; icon will not be embedded."
    # Create an empty file to prevent the build from failing
    touch resources.rcc.cpp
fi

# 5. Compile and link GUI
echo "[5/5] Compiling Qt6 GUI..."
# Set platform-specific rpath
case "$UNAME_OUT" in
    MINGW*|MSYS*|CYGWIN*)
        RPATH_FLAGS=""
        ;;
    Darwin)
        RPATH_FLAGS="-Wl,-rpath,@executable_path"
        ;;
    *)
        RPATH_FLAGS="-Wl,-rpath,\$ORIGIN"
        ;;
esac

# Compile Windows resource file for icon embedding if present
if [ "$UNAME_OUT" = "MINGW64_NT-10.0" ] || echo "$UNAME_OUT" | grep -qi mingw; then
    if [ -f resources.rc ] && command -v windres >/dev/null 2>&1; then
        echo "Compiling Windows resource file"
        windres resources.rc -O COFF -o resources.o
        RESOURCE_OBJ="resources.o"
    else
        RESOURCE_OBJ=""
    fi
else
    RESOURCE_OBJ=""
fi

"$CXX_COMPILER" -fPIC backup-manager-gui.cpp backup-manager-gui.moc.cpp resources.rcc.cpp $RESOURCE_OBJ \
    -o backup-manager-gui \
    -std=c++17 \
    $(pkg-config --cflags --libs Qt6Widgets glib-2.0 $GIO_LIBS json-glib-1.0 libsodium) \
    -L. -ldvx3 $RPATH_FLAGS \
    -I.

# Create qt.conf for local builds (helps Qt find plugins)
echo ""
echo "Creating qt.conf for plugin path configuration..."
cat > qt.conf << 'EOF'
[Paths]
Plugins = .
EOF

# Final packaging: ensure build/Releases contains the binary for CI packaging
echo "Packaging: copying artifacts to build/Releases if produced"
PLATFORM=linux
case "$UNAME_OUT" in
        MINGW*|MSYS*|CYGWIN*) PLATFORM=windows ;;
        Darwin) PLATFORM=mac ;;
        *) PLATFORM=linux ;;
esac
ARCH=${TARGET_ARCH:-$(uname -m || true)}

if [ -n "$TARGET_ARCH" ]; then
    echo "Using TARGET_ARCH override: $TARGET_ARCH (runner reports: $(uname -m || true))"
fi
OUTDIR="build/Releases/$PLATFORM/$ARCH"
mkdir -p "$OUTDIR"

# Prefer binary without extension, then .exe, then any matching name
BIN_PATH=""
if [ -f backup-manager-gui ]; then
    BIN_PATH="backup-manager-gui"
elif [ -f backup-manager-gui.exe ]; then
    BIN_PATH="backup-manager-gui.exe"
elif compgen -G "backup-manager-gui*" >/dev/null 2>&1; then
    BIN_PATH=$(compgen -G "backup-manager-gui*" | head -n1)
elif compgen -G "build/*/backup-manager-gui*" >/dev/null 2>&1; then
    BIN_PATH=$(compgen -G "build/*/backup-manager-gui*" | head -n1)
fi

    if [ -n "$BIN_PATH" ] && [ -f "$BIN_PATH" ]; then
    echo "Found binary: $BIN_PATH"
    # Ensure executable
    chmod +x "$BIN_PATH" || true
    # Print file type and ldd for debugging
    FILE_DESC=$(file "$BIN_PATH" || true)
    echo "$FILE_DESC" || true
    if command -v ldd >/dev/null 2>&1; then
        ldd "$BIN_PATH" || true
    fi
    # Verify binary architecture matches the build arch
    FILE_DESC_LOWER=$(echo "$FILE_DESC" | tr '[:upper:]' '[:lower:]')
    case "$ARCH" in
        x86_64)
            expected_pat='x86-64|x86_64' ;;
        aarch64|arm64)
            expected_pat='aarch64|arm64' ;;
        *)
            expected_pat="$ARCH" ;;
    esac
    if ! echo "$FILE_DESC_LOWER" | grep -E "$expected_pat" >/dev/null 2>&1; then
        echo "::error::Binary architecture mismatch for $BIN_PATH. Expected: $ARCH; file reports: $FILE_DESC" && exit 1
    fi
    # Strip binary to reduce size if strip present (and if it's ELF)
    if command -v strip >/dev/null 2>&1 && echo "$FILE_DESC_LOWER" | grep -qi 'elf'; then
        strip --strip-all "$BIN_PATH" || true
    fi
    cp "$BIN_PATH" "$OUTDIR/" || true
    # Ensure lib directory exists and copy the built shared library for runtime
    mkdir -p "$OUTDIR/lib"
    # Copy libdvx3 shared lib if it was built into this tree
    if [ -f "libdvx3.$SHARED_EXT" ]; then
        cp "libdvx3.$SHARED_EXT" "$OUTDIR/lib/" || true
        echo "$OUTDIR/lib/$(basename libdvx3.$SHARED_EXT)" >> "$OUTDIR/artifacts.txt" || true
    fi
    # Record artifact path
    echo "$OUTDIR/$(basename $BIN_PATH)" >> "$OUTDIR/artifacts.txt" || true
    echo "Copied $BIN_PATH to $OUTDIR/"
    # On macOS, create a minimal .app bundle inside build/Releases so packaging can use an app
    if [ "$UNAME_OUT" = "Darwin" ]; then
        APPDIR="$OUTDIR/backup-manager-gui.app"
        mkdir -p "$APPDIR/Contents/MacOS" || true
        mkdir -p "$APPDIR/Contents/Frameworks" || true
        # Copy binary into Contents/MacOS
        cp "$OUTDIR/$(basename $BIN_PATH)" "$APPDIR/Contents/MacOS/$(basename $BIN_PATH)" || true
        chmod +x "$APPDIR/Contents/MacOS/$(basename $BIN_PATH)" || true
        # Copy libdvx3 to app frameworks as dylib if present
        if [ -f libdvx3.$SHARED_EXT ]; then
            cp libdvx3.$SHARED_EXT "$APPDIR/Contents/Frameworks/" || true
        elif [ -f build/libdvx3.$SHARED_EXT ]; then
            cp build/libdvx3.$SHARED_EXT "$APPDIR/Contents/Frameworks/" || true
        fi
        # Copy any found libb2 dylibs to frameworks
        if ls build/*/libb2*.$SHARED_EXT >/dev/null 2>&1; then
            for s in build/*/libb2*.$SHARED_EXT; do cp "$s" "$APPDIR/Contents/Frameworks/" || true; done
        fi
        echo "Created minimal app bundle at $APPDIR"
    fi
else
    echo "Warning: No backup-manager-gui binary found to package into $OUTDIR" >&2
fi


# Copy Qt platform plugins for local testing (optional but helpful)
case "$UNAME_OUT" in
    MINGW*|MSYS*|CYGWIN*)
        echo "Copying Qt platform plugins for Windows..."
        mkdir -p platforms
        
        # Try multiple possible plugin locations
        if [ -d "/mingw64/share/qt6/plugins/platforms" ]; then
            cp /mingw64/share/qt6/plugins/platforms/*.dll platforms/ 2>/dev/null || true
        elif [ -d "/mingw64/plugins/platforms" ]; then
            cp /mingw64/plugins/platforms/*.dll platforms/ 2>/dev/null || true
        elif [ -d "/mingw64/lib/qt6/plugins/platforms" ]; then
            cp /mingw64/lib/qt6/plugins/platforms/*.dll platforms/ 2>/dev/null || true
        fi
        
        if [ -f platforms/qwindows.dll ]; then
            echo "✓ Copied qwindows.dll to platforms/"
        else
            echo "⚠ Warning: Could not copy qwindows.dll - you may need to copy it manually"
        fi
        ;;
esac

echo ""
echo "✓ Build complete!"
echo ""
echo "Run with: ./backup-manager-gui"
echo ""
echo "Setting QT_QPA_PLATFORM_PLUGIN_PATH for Linux/Arch..."
if [[ "$UNAME_OUT" == "Linux" ]]; then
    export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt6/plugins/platforms
    echo "export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt6/plugins/platforms" >> env.sh
    echo "✓ QT_QPA_PLATFORM_PLUGIN_PATH set for local run."
fi
echo ""
if [ -f dvx3-backup.png ]; then
    echo "Icon embedded from dvx3-backup.png"
else
    echo "No icon found; place dvx3-backup.png in project root to customize icon."
fi
echo ""
echo "Note: qt.conf created to help Qt find platform plugins"

# If on Windows/MSYS2, use windeployqt to collect Qt dependencies into Releases folder
if command -v windeployqt >/dev/null 2>&1; then
    echo "windeployqt: deploying Qt dependencies to build/Releases"
    mkdir -p build/Releases
    if [ -f backup-manager-gui.exe ]; then
        windeployqt --dir build/Releases backup-manager-gui.exe || true
    elif [ -f backup-manager-gui ]; then
        windeployqt --dir build/Releases backup-manager-gui || true
    fi
    echo "windeployqt completed; contents of build/Releases:"; ls -la build/Releases || true
fi

# If windeployqt put files under build/Releases, copy them to top-level Releases for CI packaging
if [ -d build/Releases ]; then
    mkdir -p Releases
    cp -r build/Releases/* Releases/ 2>/dev/null || true
fi
