/* dvx3.vapi generated by valac 0.56.18-dirty, do not modify. */

namespace Dvx3 {
	[CCode (cheader_filename = "dvx3.h")]
	public delegate void ProgressCallback (uint64 processed, uint64 total, uint64 output_bytes);
	[CCode (cheader_filename = "dvx3.h")]
	public const uint ARGON_M;
	[CCode (cheader_filename = "dvx3.h")]
	public const uint ARGON_P;
	[CCode (cheader_filename = "dvx3.h")]
	public const uint ARGON_T;
	[CCode (cheader_filename = "dvx3.h")]
	public const size_t CHUNK_SIZE;
	[CCode (cheader_filename = "dvx3.h")]
	public const size_t HEADER_RESERVE;
	[CCode (cheader_filename = "dvx3.h")]
	public static void decrypt (GLib.File enc_file, GLib.File dst_dir, string password, Dvx3.ProgressCallback? progress = null) throws GLib.Error;
	[CCode (cheader_filename = "dvx3.h")]
	public static void encrypt (GLib.File src_dir, GLib.File out_file, string password, string? exclude_path = null, Dvx3.ProgressCallback? progress = null) throws GLib.Error;
}
