/* dvx3.h generated by valac 0.56.16, the Vala compiler, do not modify */

#ifndef __DVX3_H__
#define __DVX3_H__

#include <glib.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS

#define DVX3_CHUNK_SIZE ((gsize) (1024 * 1024))
#define DVX3_ARGON_T ((guint) 2)
#define DVX3_ARGON_M ((guint) 64000)
#define DVX3_ARGON_P ((guint) 4)
#define DVX3_HEADER_RESERVE ((gsize) 512)
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

typedef void (*Dvx3ProgressCallback) (guint64 processed, guint64 total, guint64 output_bytes, gpointer user_data);

VALA_EXTERN void dvx3_encrypt (GFile* src_dir,
                   GFile* out_file,
                   const gchar* password,
                   const gchar* exclude_path,
                   Dvx3ProgressCallback progress,
                   gpointer progress_target,
                   GError** error);
VALA_EXTERN void dvx3_decrypt (GFile* enc_file,
                   GFile* dst_dir,
                   const gchar* password,
                   Dvx3ProgressCallback progress,
                   gpointer progress_target,
                   GError** error);

G_END_DECLS

#endif
