/* libdvx3.c generated by valac 0.56.18-dirty, the Vala compiler
 * generated from libdvx3.vala, do not modify */

/* -*- coding: utf-8 -*- */

#include <unistd.h>
#include <glib.h>
#include <sys/wait.h>
#include <sodium.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <glib-object.h>
#include <gobject/gvaluecollector.h>
#include <json-glib/json-glib.h>

#define DVX3_CHUNK_SIZE ((gsize) (1024 * 1024))
#define DVX3_ARGON_T ((guint) 2)
#define DVX3_ARGON_M ((guint) 64000)
#define DVX3_ARGON_P ((guint) 4)
#define DVX3_SECRETBOX_MAC crypto_secretbox_MACBYTES
#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define DVX3_TYPE_CHUNK_ENCODER (dvx3_chunk_encoder_get_type ())
#define DVX3_CHUNK_ENCODER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DVX3_TYPE_CHUNK_ENCODER, Dvx3ChunkEncoder))
#define DVX3_CHUNK_ENCODER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DVX3_TYPE_CHUNK_ENCODER, Dvx3ChunkEncoderClass))
#define DVX3_IS_CHUNK_ENCODER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DVX3_TYPE_CHUNK_ENCODER))
#define DVX3_IS_CHUNK_ENCODER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DVX3_TYPE_CHUNK_ENCODER))
#define DVX3_CHUNK_ENCODER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DVX3_TYPE_CHUNK_ENCODER, Dvx3ChunkEncoderClass))

typedef struct _Dvx3ChunkEncoder Dvx3ChunkEncoder;
typedef struct _Dvx3ChunkEncoderClass Dvx3ChunkEncoderClass;
typedef struct _Dvx3ChunkEncoderPrivate Dvx3ChunkEncoderPrivate;
typedef struct _Dvx3ParamSpecChunkEncoder Dvx3ParamSpecChunkEncoder;
typedef void (*Dvx3ProgressCallback) (guint64 processed, guint64 total, guint64 output_bytes, gpointer user_data);
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _dvx3_chunk_encoder_unref0(var) ((var == NULL) ? NULL : (var = (dvx3_chunk_encoder_unref (var), NULL)))
#define _g_bytes_unref0(var) ((var == NULL) ? NULL : (var = (g_bytes_unref (var), NULL)))

struct _Dvx3ChunkEncoder {
	GTypeInstance parent_instance;
	volatile int ref_count;
	Dvx3ChunkEncoderPrivate * priv;
	guint64 chunks;
	guint64 last_chunk_size;
	guint64 plain_bytes;
	guint64 cipher_bytes;
};

struct _Dvx3ChunkEncoderClass {
	GTypeClass parent_class;
	void (*finalize) (Dvx3ChunkEncoder *self);
};

struct _Dvx3ChunkEncoderPrivate {
	GOutputStream* output;
	guint8* master_key;
	gint master_key_length1;
	gint _master_key_size_;
};

struct _Dvx3ParamSpecChunkEncoder {
	GParamSpec parent_instance;
};

static gint Dvx3ChunkEncoder_private_offset;
static gpointer dvx3_chunk_encoder_parent_class = NULL;

VALA_EXTERN guint64 dvx3_compute_directory_size (GFile* dir,
                                     const gchar* exclude_path,
                                     GError** error);
VALA_EXTERN guint8* dvx3_uint64_to_be (guint64 v,
                           gint* result_length1);
VALA_EXTERN guint8* dvx3_uint32_to_be (guint32 v,
                           gint* result_length1);
VALA_EXTERN guint32 dvx3_be_to_uint32 (guint8* data,
                           gint data_length1);
VALA_EXTERN guint8* dvx3_random_bytes (gsize len,
                           gint* result_length1);
VALA_EXTERN guint8* dvx3_derive_key (const gchar* password,
                         guint8* salt,
                         gint salt_length1,
                         gint* result_length1,
                         GError** error);
VALA_EXTERN gpointer dvx3_chunk_encoder_ref (gpointer instance);
VALA_EXTERN void dvx3_chunk_encoder_unref (gpointer instance);
VALA_EXTERN GParamSpec* dvx3_param_spec_chunk_encoder (const gchar* name,
                                           const gchar* nick,
                                           const gchar* blurb,
                                           GType object_type,
                                           GParamFlags flags);
VALA_EXTERN void dvx3_value_set_chunk_encoder (GValue* value,
                                   gpointer v_object);
VALA_EXTERN void dvx3_value_take_chunk_encoder (GValue* value,
                                    gpointer v_object);
VALA_EXTERN gpointer dvx3_value_get_chunk_encoder (const GValue* value);
VALA_EXTERN GType dvx3_chunk_encoder_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Dvx3ChunkEncoder, dvx3_chunk_encoder_unref)
VALA_EXTERN Dvx3ChunkEncoder* dvx3_chunk_encoder_new (GOutputStream* output,
                                          guint8* master_key,
                                          gint master_key_length1);
VALA_EXTERN Dvx3ChunkEncoder* dvx3_chunk_encoder_construct (GType object_type,
                                                GOutputStream* output,
                                                guint8* master_key,
                                                gint master_key_length1);
static guint8* _vala_array_dup1 (guint8* self,
                          gssize length);
VALA_EXTERN void dvx3_chunk_encoder_write (Dvx3ChunkEncoder* self,
                               guint8* plaintext,
                               gint plaintext_length1,
                               GError** error);
VALA_EXTERN void dvx3_chunk_encoder_close (Dvx3ChunkEncoder* self,
                               GError** error);
static void dvx3_chunk_encoder_finalize (Dvx3ChunkEncoder * obj);
static GType dvx3_chunk_encoder_get_type_once (void);
VALA_EXTERN void dvx3_encrypt (GFile* src_dir,
                   GFile* out_file,
                   const gchar* password,
                   const gchar* exclude_path,
                   Dvx3ProgressCallback progress,
                   gpointer progress_target,
                   GError** error);
static void _vala_JsonNode_free (JsonNode* self);
static guint8* _vala_array_dup2 (guint8* self,
                          gssize length);
VALA_EXTERN void dvx3_decrypt (GFile* enc_file,
                   GFile* dst_dir,
                   const gchar* password,
                   Dvx3ProgressCallback progress,
                   gpointer progress_target,
                   GError** error);
static guint8* _vala_array_dup3 (guint8* self,
                          gssize length);
static guint8* _vala_array_dup4 (guint8* self,
                          gssize length);
static guint8* _vala_array_dup5 (guint8* self,
                          gssize length);
static guint8* _vala_array_dup6 (guint8* self,
                          gssize length);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static inline gpointer _vala_memdup2 (gconstpointer mem,
                        gsize byte_size);

/**
 * libdvx3 - Encrypted archive library
 * 
 * Provides secure encryption/decryption using:
 * tar → zstd → Argon2id → Secretbox (XSalsa20-Poly1305)
 */
guint64
dvx3_compute_directory_size (GFile* dir,
                             const gchar* exclude_path,
                             GError** error)
{
	guint64 total = 0ULL;
	GFileEnumerator* enumerator = NULL;
	GFileEnumerator* _tmp0_;
	GFileInfo* info = NULL;
	GError* _inner_error0_ = NULL;
	guint64 result;
	g_return_val_if_fail (dir != NULL, 0ULL);
	total = (guint64) 0;
	_tmp0_ = g_file_enumerate_children (dir, G_FILE_ATTRIBUTE_STANDARD_NAME "," G_FILE_ATTRIBUTE_STANDARD_TYPE "," G_FILE_ATTRIBUTE_STANDARD_SIZE, G_FILE_QUERY_INFO_NOFOLLOW_SYMLINKS, NULL, &_inner_error0_);
	enumerator = _tmp0_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		guint64 _tmp1_ = 0ULL;
		g_propagate_error (error, _inner_error0_);
		return _tmp1_;
	}
	info = NULL;
	while (TRUE) {
		GFileInfo* _tmp2_ = NULL;
		GFileEnumerator* _tmp3_;
		GFileInfo* _tmp4_;
		GFileInfo* _tmp6_;
		GFileInfo* _tmp7_;
		GFile* child = NULL;
		GFileInfo* _tmp8_;
		const gchar* _tmp9_;
		GFile* _tmp10_;
		gchar* child_path = NULL;
		GFile* _tmp11_;
		gchar* _tmp12_;
		gboolean _tmp13_ = FALSE;
		GFileInfo* _tmp15_;
		_tmp3_ = enumerator;
		_tmp4_ = g_file_enumerator_next_file (_tmp3_, NULL, &_inner_error0_);
		_tmp2_ = _tmp4_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			guint64 _tmp5_ = 0ULL;
			g_propagate_error (error, _inner_error0_);
			_g_object_unref0 (info);
			_g_object_unref0 (enumerator);
			return _tmp5_;
		}
		_tmp6_ = _tmp2_;
		_tmp2_ = NULL;
		_g_object_unref0 (info);
		info = _tmp6_;
		_tmp7_ = info;
		if (!(_tmp7_ != NULL)) {
			_g_object_unref0 (_tmp2_);
			break;
		}
		_tmp8_ = info;
		_tmp9_ = g_file_info_get_name (_tmp8_);
		_tmp10_ = g_file_resolve_relative_path (dir, _tmp9_);
		child = _tmp10_;
		_tmp11_ = child;
		_tmp12_ = g_file_get_path (_tmp11_);
		child_path = _tmp12_;
		if (exclude_path != NULL) {
			const gchar* _tmp14_;
			_tmp14_ = child_path;
			_tmp13_ = g_strcmp0 (_tmp14_, exclude_path) == 0;
		} else {
			_tmp13_ = FALSE;
		}
		if (_tmp13_) {
			_g_free0 (child_path);
			_g_object_unref0 (child);
			_g_object_unref0 (_tmp2_);
			continue;
		}
		_tmp15_ = info;
		if (g_file_info_get_file_type (_tmp15_) == G_FILE_TYPE_DIRECTORY) {
			guint64 _tmp16_ = 0ULL;
			GFile* _tmp17_;
			_tmp17_ = child;
			_tmp16_ = dvx3_compute_directory_size (_tmp17_, exclude_path, &_inner_error0_);
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				guint64 _tmp18_ = 0ULL;
				g_propagate_error (error, _inner_error0_);
				_g_free0 (child_path);
				_g_object_unref0 (child);
				_g_object_unref0 (_tmp2_);
				_g_object_unref0 (info);
				_g_object_unref0 (enumerator);
				return _tmp18_;
			}
			total += _tmp16_;
		} else {
			GFileInfo* _tmp19_;
			_tmp19_ = info;
			if (g_file_info_get_file_type (_tmp19_) == G_FILE_TYPE_REGULAR) {
				GFileInfo* _tmp20_;
				_tmp20_ = info;
				total += (guint64) g_file_info_get_size (_tmp20_);
			}
		}
		_g_free0 (child_path);
		_g_object_unref0 (child);
		_g_object_unref0 (_tmp2_);
	}
	result = total;
	_g_object_unref0 (info);
	_g_object_unref0 (enumerator);
	return result;
}

guint8*
dvx3_uint64_to_be (guint64 v,
                   gint* result_length1)
{
	guint8* buf = NULL;
	guint8* _tmp0_;
	gint buf_length1;
	gint _buf_size_;
	guint8* _tmp4_;
	gint _tmp4__length1;
	guint8* result;
	_tmp0_ = g_new0 (guint8, 8);
	buf = _tmp0_;
	buf_length1 = 8;
	_buf_size_ = buf_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				guint8* _tmp3_;
				gint _tmp3__length1;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				if (!(i < 8)) {
					break;
				}
				_tmp3_ = buf;
				_tmp3__length1 = buf_length1;
				_tmp3_[7 - i] = (guint8) (v >> (i * 8));
			}
		}
	}
	_tmp4_ = buf;
	_tmp4__length1 = buf_length1;
	if (result_length1) {
		*result_length1 = _tmp4__length1;
	}
	result = _tmp4_;
	return result;
}

guint8*
dvx3_uint32_to_be (guint32 v,
                   gint* result_length1)
{
	guint8* buf = NULL;
	guint8* _tmp0_;
	gint buf_length1;
	gint _buf_size_;
	guint8* _tmp4_;
	gint _tmp4__length1;
	guint8* result;
	_tmp0_ = g_new0 (guint8, 4);
	buf = _tmp0_;
	buf_length1 = 4;
	_buf_size_ = buf_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				guint8* _tmp3_;
				gint _tmp3__length1;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				if (!(i < 4)) {
					break;
				}
				_tmp3_ = buf;
				_tmp3__length1 = buf_length1;
				_tmp3_[3 - i] = (guint8) (v >> (i * 8));
			}
		}
	}
	_tmp4_ = buf;
	_tmp4__length1 = buf_length1;
	if (result_length1) {
		*result_length1 = _tmp4__length1;
	}
	result = _tmp4_;
	return result;
}

guint32
dvx3_be_to_uint32 (guint8* data,
                   gint data_length1)
{
	guint32 v = 0U;
	guint32 result;
	v = (guint32) 0;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				guint8 _tmp2_;
				if (!_tmp0_) {
					gint _tmp1_;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				if (!(i < 4)) {
					break;
				}
				_tmp2_ = data[i];
				v = (v << 8) | _tmp2_;
			}
		}
	}
	result = v;
	return result;
}

guint8*
dvx3_random_bytes (gsize len,
                   gint* result_length1)
{
	guint8* buf = NULL;
	guint8* _tmp0_;
	gint buf_length1;
	gint _buf_size_;
	guint8* _tmp1_;
	gint _tmp1__length1;
	guint8* result;
	_tmp0_ = g_new0 (guint8, len);
	buf = _tmp0_;
	buf_length1 = len;
	_buf_size_ = buf_length1;
	randombytes_buf (buf, len);
	_tmp1_ = buf;
	_tmp1__length1 = buf_length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}

guint8*
dvx3_derive_key (const gchar* password,
                 guint8* salt,
                 gint salt_length1,
                 gint* result_length1,
                 GError** error)
{
	guint8* key = NULL;
	guint8* _tmp0_;
	gint key_length1;
	gint _key_size_;
	gint ret = 0;
	guint8* _tmp1_;
	gint _tmp1__length1;
	gint _tmp2_;
	gint _tmp3_;
	guint8* _tmp5_;
	gint _tmp5__length1;
	GError* _inner_error0_ = NULL;
	guint8* result;
	g_return_val_if_fail (password != NULL, NULL);
	_tmp0_ = g_new0 (guint8, crypto_secretbox_KEYBYTES);
	key = _tmp0_;
	key_length1 = crypto_secretbox_KEYBYTES;
	_key_size_ = key_length1;
	_tmp1_ = key;
	_tmp1__length1 = key_length1;
	_tmp2_ = strlen (password);
	_tmp3_ = _tmp2_;
	ret = crypto_pwhash (_tmp1_, (gulong) crypto_secretbox_KEYBYTES, password, (gulong) _tmp3_, salt, (gulong) DVX3_ARGON_T, (gsize) (DVX3_ARGON_M * 1024), crypto_pwhash_ALG_ARGON2ID13);
	if (ret != 0) {
		GError* _tmp4_;
		_tmp4_ = g_error_new_literal (G_IO_ERROR, G_IO_ERROR_FAILED, "Argon2 key derivation failed");
		_inner_error0_ = _tmp4_;
		g_propagate_error (error, _inner_error0_);
		key = (g_free (key), NULL);
		return NULL;
	}
	_tmp5_ = key;
	_tmp5__length1 = key_length1;
	if (result_length1) {
		*result_length1 = _tmp5__length1;
	}
	result = _tmp5_;
	return result;
}

static inline gpointer
dvx3_chunk_encoder_get_instance_private (Dvx3ChunkEncoder* self)
{
	return G_STRUCT_MEMBER_P (self, Dvx3ChunkEncoder_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static guint8*
_vala_array_dup1 (guint8* self,
                  gssize length)
{
	if (length > 0) {
		return _vala_memdup2 (self, length * sizeof (guint8));
	}
	return NULL;
}

Dvx3ChunkEncoder*
dvx3_chunk_encoder_construct (GType object_type,
                              GOutputStream* output,
                              guint8* master_key,
                              gint master_key_length1)
{
	Dvx3ChunkEncoder* self = NULL;
	GOutputStream* _tmp0_;
	guint8* _tmp1_;
	gint _tmp1__length1;
	g_return_val_if_fail (output != NULL, NULL);
	self = (Dvx3ChunkEncoder*) g_type_create_instance (object_type);
	_tmp0_ = _g_object_ref0 (output);
	_g_object_unref0 (self->priv->output);
	self->priv->output = _tmp0_;
	_tmp1_ = (master_key != NULL) ? _vala_array_dup1 (master_key, master_key_length1) : master_key;
	_tmp1__length1 = master_key_length1;
	self->priv->master_key = (g_free (self->priv->master_key), NULL);
	self->priv->master_key = _tmp1_;
	self->priv->master_key_length1 = _tmp1__length1;
	self->priv->_master_key_size_ = self->priv->master_key_length1;
	return self;
}

Dvx3ChunkEncoder*
dvx3_chunk_encoder_new (GOutputStream* output,
                        guint8* master_key,
                        gint master_key_length1)
{
	return dvx3_chunk_encoder_construct (DVX3_TYPE_CHUNK_ENCODER, output, master_key, master_key_length1);
}

void
dvx3_chunk_encoder_write (Dvx3ChunkEncoder* self,
                          guint8* plaintext,
                          gint plaintext_length1,
                          GError** error)
{
	guint8* nonce = NULL;
	gint _tmp0_ = 0;
	guint8* _tmp1_;
	gint nonce_length1;
	gint _nonce_size_;
	guint8* ciphertext = NULL;
	guint8* _tmp2_;
	gint ciphertext_length1;
	gint _ciphertext_size_;
	gint ret = 0;
	guint8* _tmp3_;
	gint _tmp3__length1;
	guint8* _tmp4_;
	gint _tmp4__length1;
	guint8* _tmp5_;
	gint _tmp5__length1;
	gsize written = 0UL;
	GOutputStream* _tmp7_;
	guint8* _tmp8_;
	gint _tmp8__length1;
	gsize _tmp9_ = 0UL;
	GOutputStream* _tmp10_;
	guint8* _tmp11_;
	gint _tmp11__length1;
	gsize _tmp12_ = 0UL;
	guint64 _tmp13_;
	guint8* _tmp14_;
	gint _tmp14__length1;
	guint8* _tmp15_;
	gint _tmp15__length1;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp1_ = dvx3_random_bytes (crypto_secretbox_NONCEBYTES, &_tmp0_);
	nonce = _tmp1_;
	nonce_length1 = _tmp0_;
	_nonce_size_ = nonce_length1;
	_tmp2_ = g_new0 (guint8, plaintext_length1 + ((gint) DVX3_SECRETBOX_MAC));
	ciphertext = _tmp2_;
	ciphertext_length1 = plaintext_length1 + ((gint) DVX3_SECRETBOX_MAC);
	_ciphertext_size_ = ciphertext_length1;
	_tmp3_ = ciphertext;
	_tmp3__length1 = ciphertext_length1;
	_tmp4_ = nonce;
	_tmp4__length1 = nonce_length1;
	_tmp5_ = self->priv->master_key;
	_tmp5__length1 = self->priv->master_key_length1;
	ret = crypto_secretbox_easy (_tmp3_, plaintext, (gulong) plaintext_length1, _tmp4_, _tmp5_);
	if (ret != 0) {
		GError* _tmp6_;
		_tmp6_ = g_error_new_literal (G_IO_ERROR, G_IO_ERROR_FAILED, "Encryption failed");
		_inner_error0_ = _tmp6_;
		g_propagate_error (error, _inner_error0_);
		ciphertext = (g_free (ciphertext), NULL);
		nonce = (g_free (nonce), NULL);
		return;
	}
	_tmp7_ = self->priv->output;
	_tmp8_ = nonce;
	_tmp8__length1 = nonce_length1;
	g_output_stream_write_all (_tmp7_, _tmp8_, (gsize) _tmp8__length1, &_tmp9_, NULL, &_inner_error0_);
	written = _tmp9_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		ciphertext = (g_free (ciphertext), NULL);
		nonce = (g_free (nonce), NULL);
		return;
	}
	_tmp10_ = self->priv->output;
	_tmp11_ = ciphertext;
	_tmp11__length1 = ciphertext_length1;
	g_output_stream_write_all (_tmp10_, _tmp11_, (gsize) _tmp11__length1, &_tmp12_, NULL, &_inner_error0_);
	written = _tmp12_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		ciphertext = (g_free (ciphertext), NULL);
		nonce = (g_free (nonce), NULL);
		return;
	}
	_tmp13_ = self->chunks;
	self->chunks = _tmp13_ + 1;
	self->last_chunk_size = (guint64) plaintext_length1;
	self->plain_bytes = self->plain_bytes + ((guint64) plaintext_length1);
	_tmp14_ = nonce;
	_tmp14__length1 = nonce_length1;
	_tmp15_ = ciphertext;
	_tmp15__length1 = ciphertext_length1;
	self->cipher_bytes = self->cipher_bytes + ((guint64) (_tmp14__length1 + _tmp15__length1));
	ciphertext = (g_free (ciphertext), NULL);
	nonce = (g_free (nonce), NULL);
}

void
dvx3_chunk_encoder_close (Dvx3ChunkEncoder* self,
                          GError** error)
{
	GOutputStream* _tmp0_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->output;
	g_output_stream_flush (_tmp0_, NULL, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		return;
	}
}

static void
dvx3_value_chunk_encoder_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
dvx3_value_chunk_encoder_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		dvx3_chunk_encoder_unref (value->data[0].v_pointer);
	}
}

static void
dvx3_value_chunk_encoder_copy_value (const GValue* src_value,
                                     GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = dvx3_chunk_encoder_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
dvx3_value_chunk_encoder_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
dvx3_value_chunk_encoder_collect_value (GValue* value,
                                        guint n_collect_values,
                                        GTypeCValue* collect_values,
                                        guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		Dvx3ChunkEncoder * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = dvx3_chunk_encoder_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
dvx3_value_chunk_encoder_lcopy_value (const GValue* value,
                                      guint n_collect_values,
                                      GTypeCValue* collect_values,
                                      guint collect_flags)
{
	Dvx3ChunkEncoder ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = dvx3_chunk_encoder_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
dvx3_param_spec_chunk_encoder (const gchar* name,
                               const gchar* nick,
                               const gchar* blurb,
                               GType object_type,
                               GParamFlags flags)
{
	Dvx3ParamSpecChunkEncoder* spec;
	g_return_val_if_fail (g_type_is_a (object_type, DVX3_TYPE_CHUNK_ENCODER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
dvx3_value_get_chunk_encoder (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, DVX3_TYPE_CHUNK_ENCODER), NULL);
	return value->data[0].v_pointer;
}

void
dvx3_value_set_chunk_encoder (GValue* value,
                              gpointer v_object)
{
	Dvx3ChunkEncoder * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, DVX3_TYPE_CHUNK_ENCODER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, DVX3_TYPE_CHUNK_ENCODER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		dvx3_chunk_encoder_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		dvx3_chunk_encoder_unref (old);
	}
}

void
dvx3_value_take_chunk_encoder (GValue* value,
                               gpointer v_object)
{
	Dvx3ChunkEncoder * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, DVX3_TYPE_CHUNK_ENCODER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, DVX3_TYPE_CHUNK_ENCODER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		dvx3_chunk_encoder_unref (old);
	}
}

static void
dvx3_chunk_encoder_class_init (Dvx3ChunkEncoderClass * klass,
                               gpointer klass_data)
{
	dvx3_chunk_encoder_parent_class = g_type_class_peek_parent (klass);
	((Dvx3ChunkEncoderClass *) klass)->finalize = dvx3_chunk_encoder_finalize;
	g_type_class_adjust_private_offset (klass, &Dvx3ChunkEncoder_private_offset);
}

static void
dvx3_chunk_encoder_instance_init (Dvx3ChunkEncoder * self,
                                  gpointer klass)
{
	self->priv = dvx3_chunk_encoder_get_instance_private (self);
	self->chunks = (guint64) 0;
	self->last_chunk_size = (guint64) 0;
	self->plain_bytes = (guint64) 0;
	self->cipher_bytes = (guint64) 0;
	self->ref_count = 1;
}

static void
dvx3_chunk_encoder_finalize (Dvx3ChunkEncoder * obj)
{
	Dvx3ChunkEncoder * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DVX3_TYPE_CHUNK_ENCODER, Dvx3ChunkEncoder);
	g_signal_handlers_destroy (self);
	_g_object_unref0 (self->priv->output);
	self->priv->master_key = (g_free (self->priv->master_key), NULL);
}

static GType
dvx3_chunk_encoder_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { dvx3_value_chunk_encoder_init, dvx3_value_chunk_encoder_free_value, dvx3_value_chunk_encoder_copy_value, dvx3_value_chunk_encoder_peek_pointer, "p", dvx3_value_chunk_encoder_collect_value, "p", dvx3_value_chunk_encoder_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (Dvx3ChunkEncoderClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dvx3_chunk_encoder_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Dvx3ChunkEncoder), 0, (GInstanceInitFunc) dvx3_chunk_encoder_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType dvx3_chunk_encoder_type_id;
	dvx3_chunk_encoder_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Dvx3ChunkEncoder", &g_define_type_info, &g_define_type_fundamental_info, 0);
	Dvx3ChunkEncoder_private_offset = g_type_add_instance_private (dvx3_chunk_encoder_type_id, sizeof (Dvx3ChunkEncoderPrivate));
	return dvx3_chunk_encoder_type_id;
}

GType
dvx3_chunk_encoder_get_type (void)
{
	static volatile gsize dvx3_chunk_encoder_type_id__once = 0;
	if (g_once_init_enter (&dvx3_chunk_encoder_type_id__once)) {
		GType dvx3_chunk_encoder_type_id;
		dvx3_chunk_encoder_type_id = dvx3_chunk_encoder_get_type_once ();
		g_once_init_leave (&dvx3_chunk_encoder_type_id__once, dvx3_chunk_encoder_type_id);
	}
	return dvx3_chunk_encoder_type_id__once;
}

gpointer
dvx3_chunk_encoder_ref (gpointer instance)
{
	Dvx3ChunkEncoder * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
dvx3_chunk_encoder_unref (gpointer instance)
{
	Dvx3ChunkEncoder * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		DVX3_CHUNK_ENCODER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

/**
     * Encrypt a directory to an encrypted archive
     * 
     * @param src_dir Source directory to encrypt
     * @param out_file Output .dvx3 file
     * @param password Password for encryption
     * @param exclude_path Optional path to exclude from archive (for in-place mode)
     * @param progress Optional progress callback
     * @throws Error on encryption failure
     */
static gpointer
_json_object_ref0 (gpointer self)
{
	return self ? json_object_ref (self) : NULL;
}

static gchar
string_get (const gchar* self,
            glong index)
{
	gchar _tmp0_;
	gchar result;
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = ((gchar*) self)[index];
	result = _tmp0_;
	return result;
}

static void
_vala_JsonNode_free (JsonNode* self)
{
	g_boxed_free (json_node_get_type (), self);
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result;
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
	end = _tmp0_;
	_tmp1_ = end;
	if (_tmp1_ == NULL) {
		result = maxlen;
		return result;
	} else {
		gchar* _tmp2_;
		_tmp2_ = end;
		result = (glong) (_tmp2_ - str);
		return result;
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (offset >= ((glong) 0)) {
		_tmp0_ = len >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		string_length = string_strnlen ((gchar*) self, offset + len);
	} else {
		gint _tmp1_;
		gint _tmp2_;
		_tmp1_ = strlen (self);
		_tmp2_ = _tmp1_;
		string_length = (glong) _tmp2_;
	}
	if (offset < ((glong) 0)) {
		offset = string_length + offset;
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
	} else {
		g_return_val_if_fail (offset <= string_length, NULL);
	}
	if (len < ((glong) 0)) {
		len = string_length - offset;
	}
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
	result = _tmp3_;
	return result;
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	if ((*((gchar*) self)) == '\0') {
		_tmp1_ = TRUE;
	} else {
		_tmp1_ = (*((gchar*) old)) == '\0';
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
	}
	if (_tmp0_) {
		gchar* _tmp2_;
		_tmp2_ = g_strdup (self);
		result = _tmp2_;
		return result;
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		_tmp3_ = g_regex_escape_string (old, -1);
		_tmp4_ = _tmp3_;
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
		_tmp6_ = _tmp5_;
		_g_free0 (_tmp4_);
		regex = _tmp6_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp8_ = regex;
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
		_tmp7_ = _tmp9_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp10_ = _tmp7_;
		_tmp7_ = NULL;
		result = _tmp10_;
		_g_free0 (_tmp7_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
		g_clear_error (&_inner_error0_);
		g_assert_not_reached ();
	}
	__finally0:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
	g_clear_error (&_inner_error0_);
	return NULL;
}

static guint8*
_vala_array_dup2 (guint8* self,
                  gssize length)
{
	if (length > 0) {
		return _vala_memdup2 (self, length * sizeof (guint8));
	}
	return NULL;
}

void
dvx3_encrypt (GFile* src_dir,
              GFile* out_file,
              const gchar* password,
              const gchar* exclude_path,
              Dvx3ProgressCallback progress,
              gpointer progress_target,
              GError** error)
{
	gchar* src_path = NULL;
	gchar* _tmp0_;
	guint64 source_size = 0ULL;
	guint64 estimated_compressed = 0ULL;
	guint8* salt = NULL;
	gint _tmp1_ = 0;
	guint8* _tmp2_;
	gint salt_length1;
	gint _salt_size_;
	guint8* master = NULL;
	guint8* _tmp3_;
	gint _tmp3__length1;
	gint _tmp4_ = 0;
	guint8* _tmp5_;
	gint master_length1;
	gint _master_size_;
	JsonObject* placeholder_header = NULL;
	JsonObject* _tmp6_;
	JsonObject* _tmp7_;
	guint8* _tmp8_;
	gint _tmp8__length1;
	gchar* _tmp9_;
	gchar* _tmp10_;
	JsonObject* _tmp11_;
	JsonObject* _tmp12_;
	JsonObject* argon = NULL;
	JsonObject* _tmp13_;
	JsonObject* _tmp14_;
	JsonObject* _tmp15_;
	JsonObject* _tmp16_;
	JsonObject* _tmp17_;
	JsonObject* _tmp18_;
	JsonObject* _tmp19_;
	JsonObject* _tmp20_;
	JsonGenerator* gen = NULL;
	JsonGenerator* _tmp21_;
	JsonNode* root_node = NULL;
	JsonNode* _tmp22_;
	JsonNode* _tmp23_;
	JsonObject* _tmp24_;
	JsonGenerator* _tmp25_;
	JsonNode* _tmp26_;
	gchar* placeholder_json_str = NULL;
	JsonGenerator* _tmp27_;
	gchar* _tmp28_;
	guint8* placeholder_json = NULL;
	const gchar* _tmp29_;
	gint _tmp30_;
	gint _tmp31_;
	guint8* _tmp32_;
	gint placeholder_json_length1;
	gint _placeholder_json_size_;
	guint32 placeholder_len = 0U;
	guint8* _tmp40_;
	gint _tmp40__length1;
	gsize written = 0UL;
	GFileOutputStream* fout = NULL;
	GFileOutputStream* _tmp41_;
	GFileOutputStream* _tmp42_;
	gint _tmp43_ = 0;
	guint8* _tmp44_;
	guint8* _tmp45_;
	gint _tmp45__length1;
	gsize _tmp46_ = 0UL;
	GFileOutputStream* _tmp47_;
	guint8* _tmp48_;
	gint _tmp48__length1;
	gsize _tmp49_ = 0UL;
	Dvx3ChunkEncoder* encoder = NULL;
	GFileOutputStream* _tmp50_;
	guint8* _tmp51_;
	gint _tmp51__length1;
	Dvx3ChunkEncoder* _tmp52_;
	gchar** pipeline_cmd = NULL;
	gint pipeline_cmd_length1 = 0;
	gint _pipeline_cmd_size_ = 0;
	gint pipe_stdout = 0;
	GPid child_pid = 0;
	gchar** _tmp81_;
	gint _tmp81__length1;
	GPid _tmp82_ = 0;
	gint _tmp83_ = 0;
	guint64 compressed_bytes = 0ULL;
	guint8* buffer = NULL;
	guint8* _tmp84_;
	gint buffer_length1;
	gint _buffer_size_;
	Dvx3ChunkEncoder* _tmp91_;
	gint child_status = 0;
	gint _tmp92_ = 0;
	JsonObject* final_header = NULL;
	JsonObject* _tmp94_;
	JsonObject* _tmp95_;
	guint8* _tmp96_;
	gint _tmp96__length1;
	gchar* _tmp97_;
	gchar* _tmp98_;
	JsonObject* _tmp99_;
	Dvx3ChunkEncoder* _tmp100_;
	JsonObject* _tmp101_;
	Dvx3ChunkEncoder* _tmp102_;
	JsonObject* _tmp103_;
	JsonObject* _tmp104_;
	JsonObject* _tmp105_;
	JsonGenerator* _tmp106_;
	JsonNode* _tmp107_;
	JsonNode* _tmp108_;
	JsonObject* _tmp109_;
	JsonGenerator* _tmp110_;
	JsonNode* _tmp111_;
	gchar* final_json_str = NULL;
	JsonGenerator* _tmp112_;
	gchar* _tmp113_;
	guint8* final_json = NULL;
	const gchar* _tmp114_;
	gint _tmp115_;
	gint _tmp116_;
	guint8* _tmp117_;
	gint final_json_length1;
	gint _final_json_size_;
	guint32 final_len = 0U;
	guint8* _tmp125_;
	gint _tmp125__length1;
	GFileOutputStream* _tmp127_;
	GFileOutputStream* _tmp128_;
	gint _tmp129_ = 0;
	guint8* _tmp130_;
	guint8* _tmp131_;
	gint _tmp131__length1;
	gsize _tmp132_ = 0UL;
	GFileOutputStream* _tmp133_;
	guint8* _tmp134_;
	gint _tmp134__length1;
	gsize _tmp135_ = 0UL;
	GFileOutputStream* _tmp136_;
	GFileOutputStream* _tmp137_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (src_dir != NULL);
	g_return_if_fail (out_file != NULL);
	g_return_if_fail (password != NULL);
	_tmp0_ = g_file_get_path (src_dir);
	src_path = _tmp0_;
	source_size = dvx3_compute_directory_size (src_dir, exclude_path, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		_g_free0 (src_path);
		return;
	}
	estimated_compressed = source_size / 2;
	_tmp2_ = dvx3_random_bytes (crypto_pwhash_SALTBYTES, &_tmp1_);
	salt = _tmp2_;
	salt_length1 = _tmp1_;
	_salt_size_ = salt_length1;
	_tmp3_ = salt;
	_tmp3__length1 = salt_length1;
	_tmp5_ = dvx3_derive_key (password, _tmp3_, (gint) _tmp3__length1, &_tmp4_, &_inner_error0_);
	master = _tmp5_;
	master_length1 = _tmp4_;
	_master_size_ = master_length1;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		salt = (g_free (salt), NULL);
		_g_free0 (src_path);
		return;
	}
	_tmp6_ = json_object_new ();
	placeholder_header = _tmp6_;
	_tmp7_ = placeholder_header;
	_tmp8_ = salt;
	_tmp8__length1 = salt_length1;
	_tmp9_ = g_base64_encode (_tmp8_, (gint) _tmp8__length1);
	_tmp10_ = _tmp9_;
	json_object_set_string_member (_tmp7_, "salt", _tmp10_);
	_g_free0 (_tmp10_);
	_tmp11_ = placeholder_header;
	json_object_set_int_member (_tmp11_, "chunks", (gint64) 0);
	_tmp12_ = placeholder_header;
	json_object_set_int_member (_tmp12_, "last_chunk_size", (gint64) 0);
	_tmp13_ = json_object_new ();
	argon = _tmp13_;
	_tmp14_ = argon;
	json_object_set_int_member (_tmp14_, "time_cost", (gint64) DVX3_ARGON_T);
	_tmp15_ = argon;
	json_object_set_int_member (_tmp15_, "memory_kib", (gint64) DVX3_ARGON_M);
	_tmp16_ = argon;
	json_object_set_int_member (_tmp16_, "parallelism", (gint64) DVX3_ARGON_P);
	_tmp17_ = argon;
	json_object_set_string_member (_tmp17_, "type", "argon2id");
	_tmp18_ = placeholder_header;
	_tmp19_ = argon;
	_tmp20_ = _json_object_ref0 (_tmp19_);
	json_object_set_object_member (_tmp18_, "argon2", _tmp20_);
	_tmp21_ = json_generator_new ();
	gen = _tmp21_;
	_tmp22_ = json_node_new (JSON_NODE_OBJECT);
	root_node = _tmp22_;
	_tmp23_ = root_node;
	_tmp24_ = placeholder_header;
	json_node_set_object (_tmp23_, _tmp24_);
	_tmp25_ = gen;
	_tmp26_ = root_node;
	json_generator_set_root (_tmp25_, _tmp26_);
	_tmp27_ = gen;
	_tmp28_ = json_generator_to_data (_tmp27_, NULL);
	placeholder_json_str = _tmp28_;
	_tmp29_ = placeholder_json_str;
	_tmp30_ = strlen (_tmp29_);
	_tmp31_ = _tmp30_;
	_tmp32_ = g_new0 (guint8, _tmp31_);
	placeholder_json = _tmp32_;
	placeholder_json_length1 = _tmp31_;
	_placeholder_json_size_ = placeholder_json_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp33_ = FALSE;
			_tmp33_ = TRUE;
			while (TRUE) {
				const gchar* _tmp35_;
				gint _tmp36_;
				gint _tmp37_;
				guint8* _tmp38_;
				gint _tmp38__length1;
				const gchar* _tmp39_;
				if (!_tmp33_) {
					gint _tmp34_;
					_tmp34_ = i;
					i = _tmp34_ + 1;
				}
				_tmp33_ = FALSE;
				_tmp35_ = placeholder_json_str;
				_tmp36_ = strlen (_tmp35_);
				_tmp37_ = _tmp36_;
				if (!(i < _tmp37_)) {
					break;
				}
				_tmp38_ = placeholder_json;
				_tmp38__length1 = placeholder_json_length1;
				_tmp39_ = placeholder_json_str;
				_tmp38_[i] = (guint8) string_get (_tmp39_, (glong) i);
			}
		}
	}
	_tmp40_ = placeholder_json;
	_tmp40__length1 = placeholder_json_length1;
	placeholder_len = (guint32) _tmp40__length1;
	_tmp41_ = g_file_replace (out_file, NULL, FALSE, G_FILE_CREATE_PRIVATE, NULL, &_inner_error0_);
	fout = _tmp41_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		placeholder_json = (g_free (placeholder_json), NULL);
		_g_free0 (placeholder_json_str);
		__vala_JsonNode_free0 (root_node);
		_g_object_unref0 (gen);
		_json_object_unref0 (argon);
		_json_object_unref0 (placeholder_header);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_g_free0 (src_path);
		return;
	}
	_tmp42_ = fout;
	_tmp44_ = dvx3_uint32_to_be (placeholder_len, &_tmp43_);
	_tmp45_ = _tmp44_;
	_tmp45__length1 = _tmp43_;
	g_output_stream_write_all ((GOutputStream*) _tmp42_, _tmp45_, (gsize) _tmp43_, &_tmp46_, NULL, &_inner_error0_);
	written = _tmp46_;
	_tmp45_ = (g_free (_tmp45_), NULL);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		_g_object_unref0 (fout);
		placeholder_json = (g_free (placeholder_json), NULL);
		_g_free0 (placeholder_json_str);
		__vala_JsonNode_free0 (root_node);
		_g_object_unref0 (gen);
		_json_object_unref0 (argon);
		_json_object_unref0 (placeholder_header);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_g_free0 (src_path);
		return;
	}
	_tmp47_ = fout;
	_tmp48_ = placeholder_json;
	_tmp48__length1 = placeholder_json_length1;
	g_output_stream_write_all ((GOutputStream*) _tmp47_, _tmp48_, (gsize) _tmp48__length1, &_tmp49_, NULL, &_inner_error0_);
	written = _tmp49_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		_g_object_unref0 (fout);
		placeholder_json = (g_free (placeholder_json), NULL);
		_g_free0 (placeholder_json_str);
		__vala_JsonNode_free0 (root_node);
		_g_object_unref0 (gen);
		_json_object_unref0 (argon);
		_json_object_unref0 (placeholder_header);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_g_free0 (src_path);
		return;
	}
	_tmp50_ = fout;
	_tmp51_ = master;
	_tmp51__length1 = master_length1;
	_tmp52_ = dvx3_chunk_encoder_new ((GOutputStream*) _tmp50_, _tmp51_, _tmp51__length1);
	encoder = _tmp52_;
	if (exclude_path != NULL) {
		gchar* _tmp53_ = NULL;
		const gchar* _tmp54_;
		gchar* _tmp55_;
		gchar* _tmp56_;
		gboolean _tmp57_;
		gchar* exclude_rel = NULL;
		gchar* _tmp63_;
		gchar* _tmp64_;
		gchar* _tmp65_;
		const gchar* _tmp66_;
		gchar* _tmp67_;
		gchar* _tmp68_;
		const gchar* _tmp69_;
		gchar* _tmp70_;
		gchar* _tmp71_;
		gchar* _tmp72_;
		gchar** _tmp73_;
		_tmp54_ = src_path;
		_tmp55_ = g_strconcat (_tmp54_, "/", NULL);
		_tmp56_ = _tmp55_;
		_tmp57_ = g_str_has_prefix (exclude_path, _tmp56_);
		_g_free0 (_tmp56_);
		if (_tmp57_) {
			const gchar* _tmp58_;
			gint _tmp59_;
			gint _tmp60_;
			gchar* _tmp61_;
			_tmp58_ = src_path;
			_tmp59_ = strlen (_tmp58_);
			_tmp60_ = _tmp59_;
			_tmp61_ = string_substring (exclude_path, (glong) (_tmp60_ + 1), (glong) -1);
			_g_free0 (_tmp53_);
			_tmp53_ = _tmp61_;
		} else {
			gchar* _tmp62_;
			_tmp62_ = g_strdup (exclude_path);
			_g_free0 (_tmp53_);
			_tmp53_ = _tmp62_;
		}
		_tmp63_ = g_strdup (_tmp53_);
		exclude_rel = _tmp63_;
		_tmp64_ = g_strdup ("sh");
		_tmp65_ = g_strdup ("-c");
		_tmp66_ = exclude_rel;
		_tmp67_ = string_replace (_tmp66_, "'", "'\\''");
		_tmp68_ = _tmp67_;
		_tmp69_ = src_path;
		_tmp70_ = string_replace (_tmp69_, "'", "'\\''");
		_tmp71_ = _tmp70_;
		_tmp72_ = g_strdup_printf ("tar -c --exclude='%s' -C '%s' . | zstd -T16 -22 -c", _tmp68_, _tmp71_);
		_tmp73_ = g_new0 (gchar*, 3 + 1);
		_tmp73_[0] = _tmp64_;
		_tmp73_[1] = _tmp65_;
		_tmp73_[2] = _tmp72_;
		pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
		pipeline_cmd = _tmp73_;
		pipeline_cmd_length1 = 3;
		_pipeline_cmd_size_ = pipeline_cmd_length1;
		_g_free0 (_tmp71_);
		_g_free0 (_tmp68_);
		_g_free0 (exclude_rel);
		_g_free0 (_tmp53_);
	} else {
		gchar* _tmp74_;
		gchar* _tmp75_;
		const gchar* _tmp76_;
		gchar* _tmp77_;
		gchar* _tmp78_;
		gchar* _tmp79_;
		gchar** _tmp80_;
		_tmp74_ = g_strdup ("sh");
		_tmp75_ = g_strdup ("-c");
		_tmp76_ = src_path;
		_tmp77_ = string_replace (_tmp76_, "'", "'\\''");
		_tmp78_ = _tmp77_;
		_tmp79_ = g_strdup_printf ("tar -c -C '%s' . | zstd -T16 -22 -c", _tmp78_);
		_tmp80_ = g_new0 (gchar*, 3 + 1);
		_tmp80_[0] = _tmp74_;
		_tmp80_[1] = _tmp75_;
		_tmp80_[2] = _tmp79_;
		pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
		pipeline_cmd = _tmp80_;
		pipeline_cmd_length1 = 3;
		_pipeline_cmd_size_ = pipeline_cmd_length1;
		_g_free0 (_tmp78_);
	}
	_tmp81_ = pipeline_cmd;
	_tmp81__length1 = pipeline_cmd_length1;
	g_spawn_async_with_pipes (NULL, _tmp81_, NULL, G_SPAWN_SEARCH_PATH | G_SPAWN_DO_NOT_REAP_CHILD, NULL, NULL, &_tmp82_, NULL, &_tmp83_, NULL, &_inner_error0_);
	child_pid = _tmp82_;
	pipe_stdout = _tmp83_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
		_dvx3_chunk_encoder_unref0 (encoder);
		_g_object_unref0 (fout);
		placeholder_json = (g_free (placeholder_json), NULL);
		_g_free0 (placeholder_json_str);
		__vala_JsonNode_free0 (root_node);
		_g_object_unref0 (gen);
		_json_object_unref0 (argon);
		_json_object_unref0 (placeholder_header);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_g_free0 (src_path);
		return;
	}
	compressed_bytes = (guint64) 0;
	_tmp84_ = g_new0 (guint8, DVX3_CHUNK_SIZE);
	buffer = _tmp84_;
	buffer_length1 = DVX3_CHUNK_SIZE;
	_buffer_size_ = buffer_length1;
	while (TRUE) {
		gssize bytes_read = 0L;
		guint8* _tmp85_;
		gint _tmp85__length1;
		guint8* blk = NULL;
		guint8* _tmp86_;
		gint _tmp86__length1;
		guint8* _tmp87_;
		gint _tmp87__length1;
		gint blk_length1;
		gint _blk_size_;
		Dvx3ChunkEncoder* _tmp88_;
		guint8* _tmp89_;
		gint _tmp89__length1;
		_tmp85_ = buffer;
		_tmp85__length1 = buffer_length1;
		bytes_read = read (pipe_stdout, _tmp85_, DVX3_CHUNK_SIZE);
		if (bytes_read <= ((gssize) 0)) {
			break;
		}
		_tmp86_ = buffer;
		_tmp86__length1 = buffer_length1;
		_tmp87_ = (_tmp86_ != NULL) ? _vala_array_dup2 (_tmp86_ + 0, ((gint) bytes_read) - 0) : _tmp86_;
		_tmp87__length1 = ((gint) bytes_read) - 0;
		blk = _tmp87_;
		blk_length1 = _tmp87__length1;
		_blk_size_ = blk_length1;
		compressed_bytes += (guint64) bytes_read;
		_tmp88_ = encoder;
		_tmp89_ = blk;
		_tmp89__length1 = blk_length1;
		dvx3_chunk_encoder_write (_tmp88_, _tmp89_, (gint) _tmp89__length1, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			g_propagate_error (error, _inner_error0_);
			blk = (g_free (blk), NULL);
			buffer = (g_free (buffer), NULL);
			pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
			_dvx3_chunk_encoder_unref0 (encoder);
			_g_object_unref0 (fout);
			placeholder_json = (g_free (placeholder_json), NULL);
			_g_free0 (placeholder_json_str);
			__vala_JsonNode_free0 (root_node);
			_g_object_unref0 (gen);
			_json_object_unref0 (argon);
			_json_object_unref0 (placeholder_header);
			master = (g_free (master), NULL);
			salt = (g_free (salt), NULL);
			_g_free0 (src_path);
			return;
		}
		if (progress != NULL) {
			Dvx3ChunkEncoder* _tmp90_;
			_tmp90_ = encoder;
			progress (compressed_bytes, estimated_compressed, _tmp90_->cipher_bytes, progress_target);
		}
		blk = (g_free (blk), NULL);
	}
	close (pipe_stdout);
	_tmp91_ = encoder;
	dvx3_chunk_encoder_close (_tmp91_, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		buffer = (g_free (buffer), NULL);
		pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
		_dvx3_chunk_encoder_unref0 (encoder);
		_g_object_unref0 (fout);
		placeholder_json = (g_free (placeholder_json), NULL);
		_g_free0 (placeholder_json_str);
		__vala_JsonNode_free0 (root_node);
		_g_object_unref0 (gen);
		_json_object_unref0 (argon);
		_json_object_unref0 (placeholder_header);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_g_free0 (src_path);
		return;
	}
	waitpid ((gint) child_pid, &_tmp92_, 0);
	child_status = _tmp92_;
	if (child_status != 0) {
		GError* _tmp93_;
		_tmp93_ = g_error_new_literal (G_IO_ERROR, G_IO_ERROR_FAILED, "tar|zstd pipeline failed");
		_inner_error0_ = _tmp93_;
		g_propagate_error (error, _inner_error0_);
		buffer = (g_free (buffer), NULL);
		pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
		_dvx3_chunk_encoder_unref0 (encoder);
		_g_object_unref0 (fout);
		placeholder_json = (g_free (placeholder_json), NULL);
		_g_free0 (placeholder_json_str);
		__vala_JsonNode_free0 (root_node);
		_g_object_unref0 (gen);
		_json_object_unref0 (argon);
		_json_object_unref0 (placeholder_header);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_g_free0 (src_path);
		return;
	}
	g_spawn_close_pid (child_pid);
	_tmp94_ = json_object_new ();
	final_header = _tmp94_;
	_tmp95_ = final_header;
	_tmp96_ = salt;
	_tmp96__length1 = salt_length1;
	_tmp97_ = g_base64_encode (_tmp96_, (gint) _tmp96__length1);
	_tmp98_ = _tmp97_;
	json_object_set_string_member (_tmp95_, "salt", _tmp98_);
	_g_free0 (_tmp98_);
	_tmp99_ = final_header;
	_tmp100_ = encoder;
	json_object_set_int_member (_tmp99_, "chunks", (gint64) _tmp100_->chunks);
	_tmp101_ = final_header;
	_tmp102_ = encoder;
	json_object_set_int_member (_tmp101_, "last_chunk_size", (gint64) _tmp102_->last_chunk_size);
	_tmp103_ = final_header;
	_tmp104_ = argon;
	_tmp105_ = _json_object_ref0 (_tmp104_);
	json_object_set_object_member (_tmp103_, "argon2", _tmp105_);
	_tmp106_ = json_generator_new ();
	_g_object_unref0 (gen);
	gen = _tmp106_;
	_tmp107_ = json_node_new (JSON_NODE_OBJECT);
	__vala_JsonNode_free0 (root_node);
	root_node = _tmp107_;
	_tmp108_ = root_node;
	_tmp109_ = final_header;
	json_node_set_object (_tmp108_, _tmp109_);
	_tmp110_ = gen;
	_tmp111_ = root_node;
	json_generator_set_root (_tmp110_, _tmp111_);
	_tmp112_ = gen;
	_tmp113_ = json_generator_to_data (_tmp112_, NULL);
	final_json_str = _tmp113_;
	_tmp114_ = final_json_str;
	_tmp115_ = strlen (_tmp114_);
	_tmp116_ = _tmp115_;
	_tmp117_ = g_new0 (guint8, _tmp116_);
	final_json = _tmp117_;
	final_json_length1 = _tmp116_;
	_final_json_size_ = final_json_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp118_ = FALSE;
			_tmp118_ = TRUE;
			while (TRUE) {
				const gchar* _tmp120_;
				gint _tmp121_;
				gint _tmp122_;
				guint8* _tmp123_;
				gint _tmp123__length1;
				const gchar* _tmp124_;
				if (!_tmp118_) {
					gint _tmp119_;
					_tmp119_ = i;
					i = _tmp119_ + 1;
				}
				_tmp118_ = FALSE;
				_tmp120_ = final_json_str;
				_tmp121_ = strlen (_tmp120_);
				_tmp122_ = _tmp121_;
				if (!(i < _tmp122_)) {
					break;
				}
				_tmp123_ = final_json;
				_tmp123__length1 = final_json_length1;
				_tmp124_ = final_json_str;
				_tmp123_[i] = (guint8) string_get (_tmp124_, (glong) i);
			}
		}
	}
	_tmp125_ = final_json;
	_tmp125__length1 = final_json_length1;
	final_len = (guint32) _tmp125__length1;
	if (final_len != placeholder_len) {
		GError* _tmp126_;
		_tmp126_ = g_error_new_literal (G_IO_ERROR, G_IO_ERROR_FAILED, "Header size changed unexpectedly");
		_inner_error0_ = _tmp126_;
		g_propagate_error (error, _inner_error0_);
		final_json = (g_free (final_json), NULL);
		_g_free0 (final_json_str);
		_json_object_unref0 (final_header);
		buffer = (g_free (buffer), NULL);
		pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
		_dvx3_chunk_encoder_unref0 (encoder);
		_g_object_unref0 (fout);
		placeholder_json = (g_free (placeholder_json), NULL);
		_g_free0 (placeholder_json_str);
		__vala_JsonNode_free0 (root_node);
		_g_object_unref0 (gen);
		_json_object_unref0 (argon);
		_json_object_unref0 (placeholder_header);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_g_free0 (src_path);
		return;
	}
	_tmp127_ = fout;
	G_TYPE_INSTANCE_GET_CLASS (_tmp127_, g_file_output_stream_get_type (), GFileOutputStreamClass)->seek (_tmp127_, (gint64) 0, G_SEEK_SET, NULL, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		final_json = (g_free (final_json), NULL);
		_g_free0 (final_json_str);
		_json_object_unref0 (final_header);
		buffer = (g_free (buffer), NULL);
		pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
		_dvx3_chunk_encoder_unref0 (encoder);
		_g_object_unref0 (fout);
		placeholder_json = (g_free (placeholder_json), NULL);
		_g_free0 (placeholder_json_str);
		__vala_JsonNode_free0 (root_node);
		_g_object_unref0 (gen);
		_json_object_unref0 (argon);
		_json_object_unref0 (placeholder_header);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_g_free0 (src_path);
		return;
	}
	_tmp128_ = fout;
	_tmp130_ = dvx3_uint32_to_be (final_len, &_tmp129_);
	_tmp131_ = _tmp130_;
	_tmp131__length1 = _tmp129_;
	g_output_stream_write_all ((GOutputStream*) _tmp128_, _tmp131_, (gsize) _tmp129_, &_tmp132_, NULL, &_inner_error0_);
	written = _tmp132_;
	_tmp131_ = (g_free (_tmp131_), NULL);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		final_json = (g_free (final_json), NULL);
		_g_free0 (final_json_str);
		_json_object_unref0 (final_header);
		buffer = (g_free (buffer), NULL);
		pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
		_dvx3_chunk_encoder_unref0 (encoder);
		_g_object_unref0 (fout);
		placeholder_json = (g_free (placeholder_json), NULL);
		_g_free0 (placeholder_json_str);
		__vala_JsonNode_free0 (root_node);
		_g_object_unref0 (gen);
		_json_object_unref0 (argon);
		_json_object_unref0 (placeholder_header);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_g_free0 (src_path);
		return;
	}
	_tmp133_ = fout;
	_tmp134_ = final_json;
	_tmp134__length1 = final_json_length1;
	g_output_stream_write_all ((GOutputStream*) _tmp133_, _tmp134_, (gsize) _tmp134__length1, &_tmp135_, NULL, &_inner_error0_);
	written = _tmp135_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		final_json = (g_free (final_json), NULL);
		_g_free0 (final_json_str);
		_json_object_unref0 (final_header);
		buffer = (g_free (buffer), NULL);
		pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
		_dvx3_chunk_encoder_unref0 (encoder);
		_g_object_unref0 (fout);
		placeholder_json = (g_free (placeholder_json), NULL);
		_g_free0 (placeholder_json_str);
		__vala_JsonNode_free0 (root_node);
		_g_object_unref0 (gen);
		_json_object_unref0 (argon);
		_json_object_unref0 (placeholder_header);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_g_free0 (src_path);
		return;
	}
	_tmp136_ = fout;
	g_output_stream_flush ((GOutputStream*) _tmp136_, NULL, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		final_json = (g_free (final_json), NULL);
		_g_free0 (final_json_str);
		_json_object_unref0 (final_header);
		buffer = (g_free (buffer), NULL);
		pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
		_dvx3_chunk_encoder_unref0 (encoder);
		_g_object_unref0 (fout);
		placeholder_json = (g_free (placeholder_json), NULL);
		_g_free0 (placeholder_json_str);
		__vala_JsonNode_free0 (root_node);
		_g_object_unref0 (gen);
		_json_object_unref0 (argon);
		_json_object_unref0 (placeholder_header);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_g_free0 (src_path);
		return;
	}
	_tmp137_ = fout;
	g_output_stream_close ((GOutputStream*) _tmp137_, NULL, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		final_json = (g_free (final_json), NULL);
		_g_free0 (final_json_str);
		_json_object_unref0 (final_header);
		buffer = (g_free (buffer), NULL);
		pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
		_dvx3_chunk_encoder_unref0 (encoder);
		_g_object_unref0 (fout);
		placeholder_json = (g_free (placeholder_json), NULL);
		_g_free0 (placeholder_json_str);
		__vala_JsonNode_free0 (root_node);
		_g_object_unref0 (gen);
		_json_object_unref0 (argon);
		_json_object_unref0 (placeholder_header);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_g_free0 (src_path);
		return;
	}
	final_json = (g_free (final_json), NULL);
	_g_free0 (final_json_str);
	_json_object_unref0 (final_header);
	buffer = (g_free (buffer), NULL);
	pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
	_dvx3_chunk_encoder_unref0 (encoder);
	_g_object_unref0 (fout);
	placeholder_json = (g_free (placeholder_json), NULL);
	_g_free0 (placeholder_json_str);
	__vala_JsonNode_free0 (root_node);
	_g_object_unref0 (gen);
	_json_object_unref0 (argon);
	_json_object_unref0 (placeholder_header);
	master = (g_free (master), NULL);
	salt = (g_free (salt), NULL);
	_g_free0 (src_path);
}

/**
     * Decrypt an encrypted archive to a directory
     * 
     * @param enc_file Encrypted .dvx3 file
     * @param dst_dir Destination directory to extract to
     * @param password Password for decryption
     * @param progress Optional progress callback
     * @throws Error on decryption failure
     */
static guint8*
_vala_array_dup3 (guint8* self,
                  gssize length)
{
	if (length > 0) {
		return _vala_memdup2 (self, length * sizeof (guint8));
	}
	return NULL;
}

static guint8*
_vala_array_dup4 (guint8* self,
                  gssize length)
{
	if (length > 0) {
		return _vala_memdup2 (self, length * sizeof (guint8));
	}
	return NULL;
}

static guint8*
_vala_array_dup5 (guint8* self,
                  gssize length)
{
	if (length > 0) {
		return _vala_memdup2 (self, length * sizeof (guint8));
	}
	return NULL;
}

static guint8*
_vala_array_dup6 (guint8* self,
                  gssize length)
{
	if (length > 0) {
		return _vala_memdup2 (self, length * sizeof (guint8));
	}
	return NULL;
}

void
dvx3_decrypt (GFile* enc_file,
              GFile* dst_dir,
              const gchar* password,
              Dvx3ProgressCallback progress,
              gpointer progress_target,
              GError** error)
{
	GFileInfo* enc_info = NULL;
	GFileInfo* _tmp0_;
	guint64 enc_bytes = 0ULL;
	GFileInfo* _tmp1_;
	GFileInputStream* fin = NULL;
	GFileInputStream* _tmp2_;
	GBytes* _tmp3_ = NULL;
	GFileInputStream* _tmp4_;
	GBytes* _tmp5_;
	guint8* len_buf = NULL;
	gsize _tmp6_ = 0;
	guint8* _tmp7_;
	guint8* _tmp8_;
	gint _tmp8__length1;
	gint len_buf_length1;
	gint _len_buf_size_;
	guint8* _tmp9_;
	gint _tmp9__length1;
	guint32 hlen = 0U;
	guint8* _tmp11_;
	gint _tmp11__length1;
	GBytes* _tmp12_ = NULL;
	GFileInputStream* _tmp13_;
	GBytes* _tmp14_;
	guint8* hdr_json = NULL;
	gsize _tmp15_ = 0;
	guint8* _tmp16_;
	guint8* _tmp17_;
	gint _tmp17__length1;
	gint hdr_json_length1;
	gint _hdr_json_size_;
	JsonParser* parser = NULL;
	JsonParser* _tmp18_;
	JsonParser* _tmp19_;
	guint8* _tmp20_;
	gint _tmp20__length1;
	guint8* _tmp21_;
	gint _tmp21__length1;
	JsonObject* hdr = NULL;
	JsonParser* _tmp22_;
	JsonNode* _tmp23_;
	JsonObject* _tmp24_;
	JsonObject* _tmp25_;
	guchar* salt = NULL;
	JsonObject* _tmp26_;
	const gchar* _tmp27_;
	gsize _tmp28_ = 0;
	guchar* _tmp29_;
	gint salt_length1;
	gint _salt_size_;
	guint8* master = NULL;
	guchar* _tmp30_;
	gint _tmp30__length1;
	gint _tmp31_ = 0;
	guint8* _tmp32_;
	gint master_length1;
	gint _master_size_;
	guint64 chunks = 0ULL;
	JsonObject* _tmp33_;
	guint64 last = 0ULL;
	JsonObject* _tmp34_;
	guint64 cipher_total = 0ULL;
	guint64 processed_cipher = 0ULL;
	guint64 plain_emitted = 0ULL;
	gchar** pipeline_cmd = NULL;
	gchar* _tmp35_;
	gchar* _tmp36_;
	gchar* _tmp37_;
	gchar* _tmp38_;
	gchar* _tmp39_;
	gchar* _tmp40_;
	gchar* _tmp41_;
	gchar** _tmp42_;
	gchar** _tmp43_;
	gint _tmp43__length1;
	gint pipeline_cmd_length1;
	gint _pipeline_cmd_size_;
	gint pipe_stdin = 0;
	GPid child_pid = 0;
	gchar** _tmp44_;
	gint _tmp44__length1;
	GPid _tmp45_ = 0;
	gint _tmp46_ = 0;
	GFileInputStream* _tmp89_;
	gint child_status = 0;
	gint _tmp90_ = 0;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (enc_file != NULL);
	g_return_if_fail (dst_dir != NULL);
	g_return_if_fail (password != NULL);
	_tmp0_ = g_file_query_info (enc_file, G_FILE_ATTRIBUTE_STANDARD_SIZE, G_FILE_QUERY_INFO_NONE, NULL, &_inner_error0_);
	enc_info = _tmp0_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		return;
	}
	_tmp1_ = enc_info;
	enc_bytes = g_file_info_get_attribute_uint64 (_tmp1_, G_FILE_ATTRIBUTE_STANDARD_SIZE);
	_tmp2_ = g_file_read (enc_file, NULL, &_inner_error0_);
	fin = _tmp2_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		_g_object_unref0 (enc_info);
		return;
	}
	_tmp4_ = fin;
	_tmp5_ = g_input_stream_read_bytes ((GInputStream*) _tmp4_, (gsize) 4, NULL, &_inner_error0_);
	_tmp3_ = _tmp5_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		_g_object_unref0 (fin);
		_g_object_unref0 (enc_info);
		return;
	}
	_tmp7_ = g_bytes_get_data (_tmp3_, &_tmp6_);
	_tmp8_ = (_tmp7_ != NULL) ? _vala_array_dup3 (_tmp7_, _tmp6_) : _tmp7_;
	_tmp8__length1 = _tmp6_;
	len_buf = _tmp8_;
	len_buf_length1 = _tmp8__length1;
	_len_buf_size_ = len_buf_length1;
	_tmp9_ = len_buf;
	_tmp9__length1 = len_buf_length1;
	if (_tmp9__length1 != 4) {
		GError* _tmp10_;
		_tmp10_ = g_error_new_literal (G_IO_ERROR, G_IO_ERROR_FAILED, "Missing header length");
		_inner_error0_ = _tmp10_;
		g_propagate_error (error, _inner_error0_);
		len_buf = (g_free (len_buf), NULL);
		_g_bytes_unref0 (_tmp3_);
		_g_object_unref0 (fin);
		_g_object_unref0 (enc_info);
		return;
	}
	_tmp11_ = len_buf;
	_tmp11__length1 = len_buf_length1;
	hlen = dvx3_be_to_uint32 (_tmp11_, (gint) _tmp11__length1);
	_tmp13_ = fin;
	_tmp14_ = g_input_stream_read_bytes ((GInputStream*) _tmp13_, (gsize) hlen, NULL, &_inner_error0_);
	_tmp12_ = _tmp14_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		len_buf = (g_free (len_buf), NULL);
		_g_bytes_unref0 (_tmp3_);
		_g_object_unref0 (fin);
		_g_object_unref0 (enc_info);
		return;
	}
	_tmp16_ = g_bytes_get_data (_tmp12_, &_tmp15_);
	_tmp17_ = (_tmp16_ != NULL) ? _vala_array_dup4 (_tmp16_, _tmp15_) : _tmp16_;
	_tmp17__length1 = _tmp15_;
	hdr_json = _tmp17_;
	hdr_json_length1 = _tmp17__length1;
	_hdr_json_size_ = hdr_json_length1;
	_tmp18_ = json_parser_new ();
	parser = _tmp18_;
	_tmp19_ = parser;
	_tmp20_ = hdr_json;
	_tmp20__length1 = hdr_json_length1;
	_tmp21_ = hdr_json;
	_tmp21__length1 = hdr_json_length1;
	json_parser_load_from_data (_tmp19_, (const gchar*) _tmp20_, (gssize) _tmp21__length1, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		_g_object_unref0 (parser);
		hdr_json = (g_free (hdr_json), NULL);
		_g_bytes_unref0 (_tmp12_);
		len_buf = (g_free (len_buf), NULL);
		_g_bytes_unref0 (_tmp3_);
		_g_object_unref0 (fin);
		_g_object_unref0 (enc_info);
		return;
	}
	_tmp22_ = parser;
	_tmp23_ = json_parser_get_root (_tmp22_);
	_tmp24_ = json_node_get_object (_tmp23_);
	_tmp25_ = _json_object_ref0 (_tmp24_);
	hdr = _tmp25_;
	_tmp26_ = hdr;
	_tmp27_ = json_object_get_string_member (_tmp26_, "salt");
	_tmp29_ = g_base64_decode (_tmp27_, &_tmp28_);
	salt = _tmp29_;
	salt_length1 = _tmp28_;
	_salt_size_ = salt_length1;
	_tmp30_ = salt;
	_tmp30__length1 = salt_length1;
	_tmp32_ = dvx3_derive_key (password, _tmp30_, (gint) _tmp30__length1, &_tmp31_, &_inner_error0_);
	master = _tmp32_;
	master_length1 = _tmp31_;
	_master_size_ = master_length1;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		salt = (g_free (salt), NULL);
		_json_object_unref0 (hdr);
		_g_object_unref0 (parser);
		hdr_json = (g_free (hdr_json), NULL);
		_g_bytes_unref0 (_tmp12_);
		len_buf = (g_free (len_buf), NULL);
		_g_bytes_unref0 (_tmp3_);
		_g_object_unref0 (fin);
		_g_object_unref0 (enc_info);
		return;
	}
	_tmp33_ = hdr;
	chunks = (guint64) json_object_get_int_member (_tmp33_, "chunks");
	_tmp34_ = hdr;
	last = (guint64) json_object_get_int_member (_tmp34_, "last_chunk_size");
	cipher_total = (guint64) 0;
	if (enc_bytes > ((guint64) (4 + hlen))) {
		cipher_total = enc_bytes - ((guint64) (4 + hlen));
	}
	processed_cipher = (guint64) 0;
	plain_emitted = (guint64) 0;
	g_file_make_directory_with_parents (dst_dir, NULL, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_json_object_unref0 (hdr);
		_g_object_unref0 (parser);
		hdr_json = (g_free (hdr_json), NULL);
		_g_bytes_unref0 (_tmp12_);
		len_buf = (g_free (len_buf), NULL);
		_g_bytes_unref0 (_tmp3_);
		_g_object_unref0 (fin);
		_g_object_unref0 (enc_info);
		return;
	}
	_tmp35_ = g_strdup ("sh");
	_tmp36_ = g_strdup ("-c");
	_tmp37_ = g_file_get_path (dst_dir);
	_tmp38_ = _tmp37_;
	_tmp39_ = string_replace (_tmp38_, "'", "'\\''");
	_tmp40_ = _tmp39_;
	_tmp41_ = g_strdup_printf ("zstd -d -c | tar -x -C '%s'", _tmp40_);
	_tmp42_ = g_new0 (gchar*, 3 + 1);
	_tmp42_[0] = _tmp35_;
	_tmp42_[1] = _tmp36_;
	_tmp42_[2] = _tmp41_;
	_tmp43_ = _tmp42_;
	_tmp43__length1 = 3;
	_g_free0 (_tmp40_);
	_g_free0 (_tmp38_);
	pipeline_cmd = _tmp43_;
	pipeline_cmd_length1 = _tmp43__length1;
	_pipeline_cmd_size_ = pipeline_cmd_length1;
	_tmp44_ = pipeline_cmd;
	_tmp44__length1 = pipeline_cmd_length1;
	g_spawn_async_with_pipes (NULL, _tmp44_, NULL, G_SPAWN_SEARCH_PATH | G_SPAWN_DO_NOT_REAP_CHILD, NULL, NULL, &_tmp45_, &_tmp46_, NULL, NULL, &_inner_error0_);
	child_pid = _tmp45_;
	pipe_stdin = _tmp46_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_json_object_unref0 (hdr);
		_g_object_unref0 (parser);
		hdr_json = (g_free (hdr_json), NULL);
		_g_bytes_unref0 (_tmp12_);
		len_buf = (g_free (len_buf), NULL);
		_g_bytes_unref0 (_tmp3_);
		_g_object_unref0 (fin);
		_g_object_unref0 (enc_info);
		return;
	}
	{
		guint64 i = 0ULL;
		i = (guint64) 0;
		{
			gboolean _tmp47_ = FALSE;
			_tmp47_ = TRUE;
			while (TRUE) {
				GBytes* _tmp49_ = NULL;
				GFileInputStream* _tmp50_;
				GBytes* _tmp51_;
				guint8* nonce = NULL;
				gsize _tmp52_ = 0;
				guint8* _tmp53_;
				guint8* _tmp54_;
				gint _tmp54__length1;
				gint nonce_length1;
				gint _nonce_size_;
				guint8* _tmp55_;
				gint _tmp55__length1;
				guint64 _tmp60_ = 0ULL;
				guint64 expected_plain = 0ULL;
				guint64 ct_len = 0ULL;
				GBytes* _tmp61_ = NULL;
				GFileInputStream* _tmp62_;
				GBytes* _tmp63_;
				guint8* ct = NULL;
				gsize _tmp64_ = 0;
				guint8* _tmp65_;
				guint8* _tmp66_;
				gint _tmp66__length1;
				gint ct_length1;
				gint _ct_size_;
				guint8* _tmp67_;
				gint _tmp67__length1;
				guint8* plain = NULL;
				guint8* _tmp72_;
				gint plain_length1;
				gint _plain_size_;
				gint ret = 0;
				guint8* _tmp73_;
				gint _tmp73__length1;
				guint8* _tmp74_;
				gint _tmp74__length1;
				guint8* _tmp75_;
				gint _tmp75__length1;
				guint8* _tmp76_;
				gint _tmp76__length1;
				guint8* _tmp77_;
				gint _tmp77__length1;
				gssize written = 0L;
				guint8* _tmp82_;
				gint _tmp82__length1;
				guint8* _tmp83_;
				gint _tmp83__length1;
				guint8* _tmp84_;
				gint _tmp84__length1;
				guint8* _tmp86_;
				gint _tmp86__length1;
				guint8* _tmp87_;
				gint _tmp87__length1;
				guint8* _tmp88_;
				gint _tmp88__length1;
				if (!_tmp47_) {
					guint64 _tmp48_;
					_tmp48_ = i;
					i = _tmp48_ + 1;
				}
				_tmp47_ = FALSE;
				if (!(i < chunks)) {
					break;
				}
				_tmp50_ = fin;
				_tmp51_ = g_input_stream_read_bytes ((GInputStream*) _tmp50_, (gsize) ((guint) crypto_secretbox_NONCEBYTES), NULL, &_inner_error0_);
				_tmp49_ = _tmp51_;
				if (G_UNLIKELY (_inner_error0_ != NULL)) {
					g_propagate_error (error, _inner_error0_);
					pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
					master = (g_free (master), NULL);
					salt = (g_free (salt), NULL);
					_json_object_unref0 (hdr);
					_g_object_unref0 (parser);
					hdr_json = (g_free (hdr_json), NULL);
					_g_bytes_unref0 (_tmp12_);
					len_buf = (g_free (len_buf), NULL);
					_g_bytes_unref0 (_tmp3_);
					_g_object_unref0 (fin);
					_g_object_unref0 (enc_info);
					return;
				}
				_tmp53_ = g_bytes_get_data (_tmp49_, &_tmp52_);
				_tmp54_ = (_tmp53_ != NULL) ? _vala_array_dup5 (_tmp53_, _tmp52_) : _tmp53_;
				_tmp54__length1 = _tmp52_;
				nonce = _tmp54_;
				nonce_length1 = _tmp54__length1;
				_nonce_size_ = nonce_length1;
				_tmp55_ = nonce;
				_tmp55__length1 = nonce_length1;
				if (((gsize) _tmp55__length1) != crypto_secretbox_NONCEBYTES) {
					gchar* _tmp56_;
					gchar* _tmp57_;
					GError* _tmp58_;
					GError* _tmp59_;
					_tmp56_ = g_strdup_printf ("Truncated nonce at chunk %llu", i);
					_tmp57_ = _tmp56_;
					_tmp58_ = g_error_new_literal (G_IO_ERROR, G_IO_ERROR_FAILED, _tmp57_);
					_tmp59_ = _tmp58_;
					_g_free0 (_tmp57_);
					_inner_error0_ = _tmp59_;
					g_propagate_error (error, _inner_error0_);
					nonce = (g_free (nonce), NULL);
					_g_bytes_unref0 (_tmp49_);
					pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
					master = (g_free (master), NULL);
					salt = (g_free (salt), NULL);
					_json_object_unref0 (hdr);
					_g_object_unref0 (parser);
					hdr_json = (g_free (hdr_json), NULL);
					_g_bytes_unref0 (_tmp12_);
					len_buf = (g_free (len_buf), NULL);
					_g_bytes_unref0 (_tmp3_);
					_g_object_unref0 (fin);
					_g_object_unref0 (enc_info);
					return;
				}
				if (i == (chunks - 1)) {
					_tmp60_ = last;
				} else {
					_tmp60_ = (guint64) DVX3_CHUNK_SIZE;
				}
				expected_plain = _tmp60_;
				ct_len = expected_plain + DVX3_SECRETBOX_MAC;
				_tmp62_ = fin;
				_tmp63_ = g_input_stream_read_bytes ((GInputStream*) _tmp62_, (gsize) ct_len, NULL, &_inner_error0_);
				_tmp61_ = _tmp63_;
				if (G_UNLIKELY (_inner_error0_ != NULL)) {
					g_propagate_error (error, _inner_error0_);
					nonce = (g_free (nonce), NULL);
					_g_bytes_unref0 (_tmp49_);
					pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
					master = (g_free (master), NULL);
					salt = (g_free (salt), NULL);
					_json_object_unref0 (hdr);
					_g_object_unref0 (parser);
					hdr_json = (g_free (hdr_json), NULL);
					_g_bytes_unref0 (_tmp12_);
					len_buf = (g_free (len_buf), NULL);
					_g_bytes_unref0 (_tmp3_);
					_g_object_unref0 (fin);
					_g_object_unref0 (enc_info);
					return;
				}
				_tmp65_ = g_bytes_get_data (_tmp61_, &_tmp64_);
				_tmp66_ = (_tmp65_ != NULL) ? _vala_array_dup6 (_tmp65_, _tmp64_) : _tmp65_;
				_tmp66__length1 = _tmp64_;
				ct = _tmp66_;
				ct_length1 = _tmp66__length1;
				_ct_size_ = ct_length1;
				_tmp67_ = ct;
				_tmp67__length1 = ct_length1;
				if (((gsize) _tmp67__length1) != ((gsize) ct_len)) {
					gchar* _tmp68_;
					gchar* _tmp69_;
					GError* _tmp70_;
					GError* _tmp71_;
					_tmp68_ = g_strdup_printf ("Truncated ciphertext at chunk %llu", i);
					_tmp69_ = _tmp68_;
					_tmp70_ = g_error_new_literal (G_IO_ERROR, G_IO_ERROR_FAILED, _tmp69_);
					_tmp71_ = _tmp70_;
					_g_free0 (_tmp69_);
					_inner_error0_ = _tmp71_;
					g_propagate_error (error, _inner_error0_);
					ct = (g_free (ct), NULL);
					_g_bytes_unref0 (_tmp61_);
					nonce = (g_free (nonce), NULL);
					_g_bytes_unref0 (_tmp49_);
					pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
					master = (g_free (master), NULL);
					salt = (g_free (salt), NULL);
					_json_object_unref0 (hdr);
					_g_object_unref0 (parser);
					hdr_json = (g_free (hdr_json), NULL);
					_g_bytes_unref0 (_tmp12_);
					len_buf = (g_free (len_buf), NULL);
					_g_bytes_unref0 (_tmp3_);
					_g_object_unref0 (fin);
					_g_object_unref0 (enc_info);
					return;
				}
				_tmp72_ = g_new0 (guint8, (gint) expected_plain);
				plain = _tmp72_;
				plain_length1 = (gint) expected_plain;
				_plain_size_ = plain_length1;
				_tmp73_ = plain;
				_tmp73__length1 = plain_length1;
				_tmp74_ = ct;
				_tmp74__length1 = ct_length1;
				_tmp75_ = ct;
				_tmp75__length1 = ct_length1;
				_tmp76_ = nonce;
				_tmp76__length1 = nonce_length1;
				_tmp77_ = master;
				_tmp77__length1 = master_length1;
				ret = crypto_secretbox_open_easy (_tmp73_, _tmp74_, (gulong) _tmp75__length1, _tmp76_, _tmp77_);
				if (ret != 0) {
					gchar* _tmp78_;
					gchar* _tmp79_;
					GError* _tmp80_;
					GError* _tmp81_;
					_tmp78_ = g_strdup_printf ("Decryption failed at chunk %llu (wrong password?)", i);
					_tmp79_ = _tmp78_;
					_tmp80_ = g_error_new_literal (G_IO_ERROR, G_IO_ERROR_FAILED, _tmp79_);
					_tmp81_ = _tmp80_;
					_g_free0 (_tmp79_);
					_inner_error0_ = _tmp81_;
					g_propagate_error (error, _inner_error0_);
					plain = (g_free (plain), NULL);
					ct = (g_free (ct), NULL);
					_g_bytes_unref0 (_tmp61_);
					nonce = (g_free (nonce), NULL);
					_g_bytes_unref0 (_tmp49_);
					pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
					master = (g_free (master), NULL);
					salt = (g_free (salt), NULL);
					_json_object_unref0 (hdr);
					_g_object_unref0 (parser);
					hdr_json = (g_free (hdr_json), NULL);
					_g_bytes_unref0 (_tmp12_);
					len_buf = (g_free (len_buf), NULL);
					_g_bytes_unref0 (_tmp3_);
					_g_object_unref0 (fin);
					_g_object_unref0 (enc_info);
					return;
				}
				_tmp82_ = plain;
				_tmp82__length1 = plain_length1;
				_tmp83_ = plain;
				_tmp83__length1 = plain_length1;
				written = write (pipe_stdin, _tmp82_, (gsize) _tmp83__length1);
				_tmp84_ = plain;
				_tmp84__length1 = plain_length1;
				if (written != ((gssize) _tmp84__length1)) {
					GError* _tmp85_;
					_tmp85_ = g_error_new_literal (G_IO_ERROR, G_IO_ERROR_FAILED, "Failed to write decrypted data to pipe");
					_inner_error0_ = _tmp85_;
					g_propagate_error (error, _inner_error0_);
					plain = (g_free (plain), NULL);
					ct = (g_free (ct), NULL);
					_g_bytes_unref0 (_tmp61_);
					nonce = (g_free (nonce), NULL);
					_g_bytes_unref0 (_tmp49_);
					pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
					master = (g_free (master), NULL);
					salt = (g_free (salt), NULL);
					_json_object_unref0 (hdr);
					_g_object_unref0 (parser);
					hdr_json = (g_free (hdr_json), NULL);
					_g_bytes_unref0 (_tmp12_);
					len_buf = (g_free (len_buf), NULL);
					_g_bytes_unref0 (_tmp3_);
					_g_object_unref0 (fin);
					_g_object_unref0 (enc_info);
					return;
				}
				_tmp86_ = nonce;
				_tmp86__length1 = nonce_length1;
				_tmp87_ = ct;
				_tmp87__length1 = ct_length1;
				processed_cipher += (guint64) (_tmp86__length1 + _tmp87__length1);
				_tmp88_ = plain;
				_tmp88__length1 = plain_length1;
				plain_emitted += (guint64) _tmp88__length1;
				if (progress != NULL) {
					progress (processed_cipher, cipher_total, plain_emitted, progress_target);
				}
				plain = (g_free (plain), NULL);
				ct = (g_free (ct), NULL);
				_g_bytes_unref0 (_tmp61_);
				nonce = (g_free (nonce), NULL);
				_g_bytes_unref0 (_tmp49_);
			}
		}
	}
	close (pipe_stdin);
	_tmp89_ = fin;
	g_input_stream_close ((GInputStream*) _tmp89_, NULL, &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_propagate_error (error, _inner_error0_);
		pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_json_object_unref0 (hdr);
		_g_object_unref0 (parser);
		hdr_json = (g_free (hdr_json), NULL);
		_g_bytes_unref0 (_tmp12_);
		len_buf = (g_free (len_buf), NULL);
		_g_bytes_unref0 (_tmp3_);
		_g_object_unref0 (fin);
		_g_object_unref0 (enc_info);
		return;
	}
	waitpid ((gint) child_pid, &_tmp90_, 0);
	child_status = _tmp90_;
	if (child_status != 0) {
		GError* _tmp91_;
		_tmp91_ = g_error_new_literal (G_IO_ERROR, G_IO_ERROR_FAILED, "Extraction pipeline failed");
		_inner_error0_ = _tmp91_;
		g_propagate_error (error, _inner_error0_);
		pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
		master = (g_free (master), NULL);
		salt = (g_free (salt), NULL);
		_json_object_unref0 (hdr);
		_g_object_unref0 (parser);
		hdr_json = (g_free (hdr_json), NULL);
		_g_bytes_unref0 (_tmp12_);
		len_buf = (g_free (len_buf), NULL);
		_g_bytes_unref0 (_tmp3_);
		_g_object_unref0 (fin);
		_g_object_unref0 (enc_info);
		return;
	}
	g_spawn_close_pid (child_pid);
	pipeline_cmd = (_vala_array_free (pipeline_cmd, pipeline_cmd_length1, (GDestroyNotify) g_free), NULL);
	master = (g_free (master), NULL);
	salt = (g_free (salt), NULL);
	_json_object_unref0 (hdr);
	_g_object_unref0 (parser);
	hdr_json = (g_free (hdr_json), NULL);
	_g_bytes_unref0 (_tmp12_);
	len_buf = (g_free (len_buf), NULL);
	_g_bytes_unref0 (_tmp3_);
	_g_object_unref0 (fin);
	_g_object_unref0 (enc_info);
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static inline gpointer
_vala_memdup2 (gconstpointer mem,
               gsize byte_size)
{
	gpointer new_mem;
	if (mem && byte_size != 0) {
		new_mem = g_malloc (byte_size);
		memcpy (new_mem, mem, byte_size);
	} else {
		new_mem = NULL;
	}
	return new_mem;
}

